### ISSUE TITLE
Segfault on \sf

### ISSUE THREAD

**Issue by mclei-asw** [okbob/pspg#10]
I always get "Segmentation fault" when trying to show SQL function source code using \sf.

**Comment by loveencounterflow** [comment]
I tried, but cannot reproduce this. When I use `\sf $function_name`, the pager is not activated no matter how small I make the terminal (but it does display). Can you supply a minimal working example?

**Comment by mclei-asw** [comment]
Used  \pset pager always as you suggested on http://okbob.blogspot.cz/2017/08/postgresql-pager-pspg-is-ready-to-work.html?m=1

Using PostgreSQL 9.4 on Debian Jessie.

```
db=# \setenv PAGER '~/bin/pspg -s 2'
db=# \pset pager always
Pager is always used.
db=# create or replace function test(a int) returns int
language plpgsql as $$
begin
  return 1;
end; $$;
CREATE FUNCTION
db=# \sf test(int)
```
Segmentation fault

**Comment by okbob** [comment]
It is working on my comp. What is last commit in your local git?

**Comment by mclei** [comment]
Confirmed, that in last version, checked today, it is OK.
