### ISSUE TITLE
Copy and Paste Disabled?

### ISSUE THREAD

**Issue by jmd8045** [okbob/pspg#100]
why is copy and paste disabled when I use pspg

**Comment by okbob** [comment]
What do you think "disabled" ?

**Comment by jmd8045** [comment]
That fixed it !

Thanks

**Comment by okbob** [comment]
:)

**Comment by jmd8045** [comment]
BTW:
Both my brother (A Lawyer) and I ( Owner of Software Company in the Financial Field) both use the and really like!

**Comment by okbob** [comment]
po 9. 9. 2019 v 21:37 odesílatel James M Doherty <notifications@github.com>
napsal:

> BTW:
> Both my brother (A Lawyer) and I ( Owner of Software Company in the
> Financial Field) both use the and really like!
>
Super :)

Thank you

Pavel

p.s. see licence note :)
