### ISSUE TITLE
ignore "\?" command

### ISSUE THREAD

**Issue by dharrigan** [okbob/pspg#104]
Hi,

```
% pspg --version                    
pspg-2.0.3
with readline (version: 0x0800)
with integrated menu
ncurses version: 6.1, patch: 20180127
ncurses with wide char support
ncurses widechar num: 1
wchar_t width: 4, max: 2147483647
```

`\setenv PAGER 'pspg -s19 --bold-labels --bold-cursor --no-mouse --line-numbers -F -g -I --only-for-tables'`

Even with `--only-for-tables` set, if one executes the `\?` command at the psql CLI, it hangs, forcing a ctrl+c to return to the psql prompt.

**Comment by okbob** [comment]
maybe there is some cycle, because in your case, psql try to run psql again. When you use `--only-for-tables`, then you should to set env variable `PSPG_PAGER` to some like `less` if you set `PAGER` to `pspg`. Or set `PSQL_PAGER` to `pspg` and `PAGER` to `less`.

**Comment by okbob** [comment]
see https://github.com/okbob/pspg/commit/8385262dcb7436f39deefc2b60c754915f306b3c

**Comment by dharrigan** [comment]
Thanks! Looking forward to the next release!
