### ISSUE TITLE
Copy of selected row/column?

### ISSUE THREAD

**Issue by dharrigan** [okbob/pspg#105]
Hi,

Would it be hard to add on the ability to copy whatever row is currently highlighted and/or if a row and column are highlighted, to copy the cell? I'm afraid my C skills are not up-to-scratch or I would offer to help! :-)

Perhaps something like shift+c to copy cell (which I think would be the most common use-case) and ctrl+shift+c to copy row.

Thank you.

-=david=-

**Comment by okbob** [comment]
Hi

út 17. 9. 2019 v 14:49 odesílatel David Harrigan <notifications@github.com>
napsal:

> Hi,
>
> Would it be hard to add on the ability to copy whatever row is currently
> highlighted and/or if a row and column are highlighted, to copy the cell?
> I'm afraid my C skills are not up-to-scratch or I would offer to help! :-)
>
Unfortunately, it is pretty hard. There is not any clipboard API for
ncurses application. The terminal applications doesn't support clipboard by
self. There are a copy paste functionality implemented by terminals.

If you disable mouse handling by pspg (ALT-M), then you can select some
area by SHIFT-MOUSE, and then with CTRL-SHIFT-C you can copy selected area
to clipboard.

Pavel

**Comment by dharrigan** [comment]
Hi,

Okay, thank you for the suggestion. That works! :)

**Comment by muhmud** [comment]
Unfortunately, this doesn't work for me in tmux, as I can only move around the visible area of the screen in copy mode.

Had a thought: would it be possible to have an option to dump the current cell, row, or resultset to the screen on exit, rather than just the visible screen area of the resultset? This would fix the issue, as then I could scroll around in the parent scroll buffer to copy the data I need.

**Comment by okbob** [comment]
Hi

út 22. 12. 2020 v 15:18 odesílatel Muhmud Ahmad <notifications@github.com>
napsal:

> Unfortunately, this doesn't work for me in tmux, as I can only move around
> the visible area of the screen in copy mode.
>
> Had a thought: would it be possible to have an option to dump the current
> cell, row, or resultset to the screen on exit, rather than just the visible
> screen area of the resultset? This would fix the issue, as then I could
> scroll around in the parent scroll buffer to copy the data I need.
>
There is a problem with missing API for clipboard for ncurses applications.
You can save the resultset to file by pressing 's'. When you disable mouse
support (Alt m), then you can copy via mouse selected area.

But copy to clipboard is hard task in ncurses terminal applications

**Comment by muhmud** [comment]
I know what you mean, however, I'm using st (simple terminal) without scrollback.

So, when I disable mouse handling for pspg, I get tmux's mouse handling, which doesn't let me scroll around the whole resultset. If I then disable tmux mouse handling, I get st's mouse handling, but because it doesn't have any scrollback (it relies on tmux), I get the same thing. I could patch st to give it scrollback, but was hoping not to have to.

Do you think it's worth looking into how [tmux](https://github.com/tmux/tmux) handles copy/paste, and doing something similar?

**Comment by okbob** [comment]
st 23. 12. 2020 v 0:48 odesílatel Muhmud Ahmad <notifications@github.com>
napsal:

> I know what you mean, however, I'm using st (simple terminal) without
> scrollback.
>
> So, when I disable mouse handling for pspg, I get tmux's mouse handling,
> which doesn't let me scroll around the whole resultset. If I then disable
> tmux mouse handling, I get st's mouse handling, but because it doesn't have
> any scrollback (it relies on tmux), I get the same thing. I could patch st
> to give it scrollback, but was hoping not to have to.
>
> Do you think it's worth looking into how tmux
> <https://github.com/tmux/tmux> handles copy/paste, and doing something
> similar?
>

tmux explicitly supports only paste - but it doesn't support inverse
direction. I searched it more time, but without success. The good direction
is using applications like xsel

https://github.com/kfish/xsel
https://opensource.com/article/19/7/xclip

but it is working only on X windows, and elsewhere it doesn't work. And X
windows is ending, and these tools sometimes don't work with Wayland well.

**Comment by okbob** [comment]
There is an possibility to use xclip on Xwindows or wl-clipboard on Wayland or pbcopy on MacOS

<pre>
wl-copy  10$'\t'202$'\r\n'30$'\t'399$'\r\n' -t application/x-libreoffice-tsvc
</pre>

**Comment by muhmud** [comment]
I've used xclip in the past to get terminal emacs to copy to the clipboard; maybe if there was a setting in the pspg config that we could put a copy script command into?

**Comment by okbob** [comment]
st 23. 12. 2020 v 7:10 odesílatel Muhmud Ahmad <notifications@github.com>
napsal:

> I've used xclip in the past to get terminal emacs to copy to the
> clipboard; maybe if there was a setting in the pspg config that we could
> put a copy script command into?
>
This is easy work. Hard work - pspg doesn't support rows, columns or range
selections and implementation of this can be pretty unpleasant work.

But a good enough solution can be to copy all or bookmarked rows to
clipboard. Data can be easily cleaned in the libreoffice in the next step.

**Comment by muhmud** [comment]
Yep, that would be good enough I think :+1:

**Comment by okbob** [comment]
The master branch now support "export" functionality -. menu "file|copy to". It is not fully finished - only text format is supported now. It support export of row, column, cell, or all content, marked lines or lines with searched pattern.

**Comment by muhmud** [comment]
Sounds fantastic, will give it try & test it out

**Comment by okbob** [comment]
should be done now

**Comment by muhmud** [comment]
Is there a keyboard shortcut I can use to it? Rather than the menu? I usually have the menu turned off

**Comment by okbob** [comment]
so 16. 1. 2021 v 8:18 odesílatel Muhmud Ahmad <notifications@github.com>
napsal:

> Is there a keyboard shortcut I can use to it? Rather than the menu? I
> usually have the menu turned off
>

you can use "Ins" - insert keyword.

When the row cursor is visible, then the row will be copied with last used
options. The default format can be specified inside the config file. When
the column cursor is visible. Then column is exported. When both cursors
are visible, then the cell is copied. When both cursors are hidden, then
all rows are exported.

**Comment by muhmud** [comment]
Genius - works really well!

Question: is there a config file I can use to change keybindings? I have `Alt+v ` mapped to something else

**Comment by okbob** [comment]
ne 17. 1. 2021 v 5:43 odesílatel Muhmud Ahmad <notifications@github.com>
napsal:

> Genius - works really well!
>
> Question: is there a config file I can use to change keybindings? I have Alt+v
> mapped to something else
>
No - it is hard coded, and I don't plan to support it now. It is relatively
a lot of work* - only few users use it - and the same consistency in
shortcuts everywhere is not bad.

But you have sources, and if you need your own shortcuts, then just modify
translate_event routine in commands.c.

It is very easy.

Regards

Pavel

> —
>

* pspg has very short life cycle, so I need to hold size of binary code
down - ensure fast start of pspg

**Comment by muhmud** [comment]
Yeah, it's no biggie, cheers Pavel!
