### ISSUE TITLE
incorrect english usage

### ISSUE THREAD

**Issue by dharrigan** [okbob/pspg#109]
https://github.com/okbob/pspg/blob/f1ffc55e063ab6257d2f301dfd0335974deee687/src/pspg.c#L3465

a better usage might be:

`cannot use watch mode when query is missing or absent`

-=david=-

**Comment by okbob** [comment]
Hi

po 28. 10. 2019 v 12:02 odesílatel David Harrigan <notifications@github.com>
napsal:

>
> https://github.com/okbob/pspg/blob/f1ffc55e063ab6257d2f301dfd0335974deee687/src/pspg.c#L3465
>
> a better usage might be:
>
> cannot use watch mode when query is missing or absent
>
should be fixed now.

please, if you can do language correction, please do it - send me pull
request. My English is very poor

Pavel

**Comment by dharrigan** [comment]
Hi,

No problemo! Thanks for fixing :-) I'll do a PR in the future :+1:
