### ISSUE TITLE
When column is frozen the output is shifted and rows are missaligned on exit.

### ISSUE THREAD

**Issue by emsi** [okbob/pspg#111]
When first column is frozen after pspg is exited the values in this column are shifted one row resulting i misaligned data upon exit.

I'm using `pspg -bX --only-for-tables --quit-if-one-screen --no-bars`. 
Example:

![image](https://user-images.githubusercontent.com/433383/67955263-9f9c7880-fbf2-11e9-9af6-7779bd9f7512.png)

The id column is frozen. Once I press `q` to exit what's left on the screen is:
![image](https://user-images.githubusercontent.com/433383/67955350-c0fd6480-fbf2-11e9-84f2-246a492b05fb.png)

As you can see the frozen column was shifted one row up while all other columns stayed.
The problem does not appear if no columns are frozen so unfreezing all columns before exiting `pspg` solves the issue.

**Comment by okbob** [comment]
I was able to reproduce this bug. I'll look on it. Thank you for report

**Comment by okbob** [comment]
should be fixed by commit ed3fcf5e9e5a0ebb7abc2fd6616f69a840f71be7

**Comment by emsi** [comment]
Wow! That was fast! Thank you! :)

**Comment by okbob** [comment]
so 2. 11. 2019 v 13:26 odesílatel Mariusz Woloszyn <notifications@github.com>
napsal:

> Wow! That was fast! Thank you! :)
>

:) Thank you for report
