### ISSUE TITLE
OS X: The Postgres library was not available at compile time

### ISSUE THREAD

**Issue by timkofu** [okbob/pspg#116]
I installed pspg via Homebrew on Catalina. On running it, I get this error:
`Query cannot be executed. The Postgres library was not available at compile time.`

**Comment by okbob** [comment]
ne 3. 11. 2019 v 20:39 odesílatel Timothy Makobu <notifications@github.com>
napsal:

> I installed pspg via Homebrew on Catalina. On running it, I get this error:
> Query cannot be executed. The Postgres library was not available at
> compile time.
>
You should to see this message when 1. you used option -q or --query, 2.
you compiled pspg without postgres support.

If bot points are true, then it is expected behave, else it should be bug.

How you run pspg?

**Comment by timkofu** [comment]
My exact command is:
`pspg -d database_name -q "select attr from table_name" -W -w 10`

**Comment by okbob** [comment]
ne 3. 11. 2019 v 21:05 odesílatel Timothy Makobu <notifications@github.com>
napsal:

> My exact command is:
> pspg -d database_name -q "select attr from table_name" -W -w 10
>
In this case, you should to have pspg compiled with postgres support

I don't know build process on MacOS, but surely you need libpq-dev, run
./configure and compile

checking for pg_config... /usr/local/pgsql/bin/pg_config
checking for PostgreSQL libraries... yes

Or you can use pspg just like pager - and then it doesn't need integrated
postgres support

**Comment by okbob** [comment]
I checked homebrew formula and was not actualized - there is missing dependency on libpq. That is basic problem - but I have not a platform where I can test it, and I know almost nothing about it, so I am not able to fix Homebrew formula.

**Comment by timkofu** [comment]
I tried compilling from source (2.5.3 release), and got this error:

```
src/pspg.c:3884:2: error: use of undeclared identifier 'rl_catch_signals'
        rl_catch_signals = 0;
        ^
src/pspg.c:3885:2: error: use of undeclared identifier 'rl_catch_sigwinch'
        rl_catch_sigwinch = 0;
        ^
```

**Comment by okbob** [comment]
st 6. 11. 2019 v 6:11 odesílatel Timothy Makobu <notifications@github.com>
napsal:

> I tried compilling from source (2.5.3 release), and got this error:
>
> src/pspg.c:3884:2: error: use of undeclared identifier 'rl_catch_signals'
>         rl_catch_signals = 0;
>         ^
> src/pspg.c:3885:2: error: use of undeclared identifier 'rl_catch_sigwinch'
>         rl_catch_sigwinch = 0;
>         ^
>
>
Did you run ./configure? What is a output.

When your configuration is not usual, then correct setup is

./autogen
./configure
make

Pavel

**Comment by okbob** [comment]
st 6. 11. 2019 v 6:19 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> st 6. 11. 2019 v 6:11 odesílatel Timothy Makobu <notifications@github.com>
> napsal:
>
>> I tried compilling from source (2.5.3 release), and got this error:
>>
>> src/pspg.c:3884:2: error: use of undeclared identifier 'rl_catch_signals'
>>         rl_catch_signals = 0;
>>         ^
>> src/pspg.c:3885:2: error: use of undeclared identifier 'rl_catch_sigwinch'
>>         rl_catch_sigwinch = 0;
>>         ^
>>
>>
> Did you run ./configure? What is a output.
>
> When your configuration is not usual, then correct setup is
>
> ./autogen
> ./configure
> make
>

you should to install readline devel package. pspg can work without it, but
it is better with it.

Pavel

**Comment by timkofu** [comment]
Here's how I'm doing it:
https://asciinema.org/a/279494

Readline 8.0.1 is installed.

**Comment by okbob** [comment]
st 6. 11. 2019 v 7:27 odesílatel Timothy Makobu <notifications@github.com>
napsal:

> Here's how I'm doing it:
> https://asciinema.org/a/279494
>
> Readline 8.0.1 is installed.
>

are you sure so your dev package is readline 8.0.1?

I read source code of this release and rl_catch_signals is used there
without any limits.

can me send your file "readline.h"?

mainly context of

/* Hex-encoded Readline version number. */
#define RL_READLINE_VERSION>0x0800<><-->/* Readline 8.0 */
#define RL_VERSION_MAJOR<-->8
#define RL_VERSION_MINOR<-->0

**Comment by timkofu** [comment]
Here you go http://sprunge.us/hLxk0M
Location: /usr/local/Cellar/readline/8.0.1/include/readline/readline.h

**Comment by okbob** [comment]
st 6. 11. 2019 v 8:07 odesílatel Timothy Makobu <notifications@github.com>
napsal:

> Here you go http://sprunge.us/hLxk0M
> Location: /usr/local/Cellar/readline/8.0.1/include/readline/readline.h
>
then I understand to nothing

extern int rl_catch_signals;

**Comment by okbob** [comment]
st 6. 11. 2019 v 8:12 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> st 6. 11. 2019 v 8:07 odesílatel Timothy Makobu <notifications@github.com>
> napsal:
>
>> Here you go http://sprunge.us/hLxk0M
>> Location: /usr/local/Cellar/readline/8.0.1/include/readline/readline.h
>>
> then I understand to nothing
>
> extern int rl_catch_signals;
>
>
It's working when you try to compile some older releases - like 2.5 or 2.2 ?

**Comment by okbob** [comment]
st 6. 11. 2019 v 8:14 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> st 6. 11. 2019 v 8:12 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
> napsal:
>
>>
>>
>> st 6. 11. 2019 v 8:07 odesílatel Timothy Makobu <notifications@github.com>
>> napsal:
>>
>>> Here you go http://sprunge.us/hLxk0M
>>> Location: /usr/local/Cellar/readline/8.0.1/include/readline/readline.h
>>>
>> then I understand to nothing
>>
>> extern int rl_catch_signals;
>>
>>
> It's working when you try to compile some older releases - like 2.5 or 2.2
> ?
>

can you check so on your computer is not any other file "realine.h" for
some older version?

**Comment by okbob** [comment]
should be fixed now - homebrew formula is fixed now https://github.com/Homebrew/homebrew-core/commit/c686536e2df235fd388b67e16f171c3a21e585b0

**Comment by timkofu** [comment]
Confirmed. It's working now.
