### ISSUE TITLE
no output and screen cleared

### ISSUE THREAD

**Issue by thorstenkampe** [okbob/pspg#117]
Starting with pspg 2.5.0 I experience the following issue: in certain SQL clients (Microsoft's `mssql-cli`), the output is shown for a quarter of a second and then the screen is cleared. Just pressing enter - for example - shows this issue. Interestingly this only happens for commands where `pspg` is invoked and directly quits because the output fits the screen.

When output is shown that does not fit the screen, `pspg` correctly display the output. After quitting `pspsg` you can actually see all the other output that was not shown before. It's as if `pspg` uses some kind of alternate screen to display the results.

The environment is Windows 10.

Please let me know if you need further information to assess the issue.

**Comment by okbob** [comment]
pá 8. 11. 2019 v 8:55 odesílatel Thorsten Kampe <notifications@github.com>
napsal:

> Starting with pspg 2.5.0 I experience the following issue: in certain SQL
> clients (Microsoft's mssql-cli), the output is shown for a quarter of a
> second and the the screen is cleared. Just pressing enter - for example -
> shows this issue. Interestingly this only happens for commands where pspg
> is invoked and directly quits because the output fits the screen.
>
> When output is shown that does not fit the screen, pspg correctly display
> the output. After quitting pspsg you can actually see all the other
> output that was not shown before. It's as if pspg uses some kind of
> alternate screen to display the results.
>
> The environment is Windows 10.
>
> Please let me know if you need further information to assess the issue.
>

older releases are ok?

please, can me send examples of your pspg settings, and some test cases?
When you can see this issue, and when it is ok.

Pavel

**Comment by okbob** [comment]
Interesting issue - I try to simulate this behave, but without success. I need more detailed test case, please.

**Comment by thorstenkampe** [comment]
Releases up to 2.1.8 are okay. The issue seems to only occur under `mssql-cli`, Microsoft's new SQL command line client for SQL server. The issue occurs on Linux and Windows but with slightly different result: on Linux the screen is not cleared but the cursor travels almost to the bottom of the screen. On Windows, the screen is cleared.

I'm attaching animated GIFs for Linux and Windows as well as the my pspg configuration.
![Linux](https://user-images.githubusercontent.com/475462/68501545-b0866300-025e-11ea-9e77-bf51921d38f1.gif)
![Windows](https://user-images.githubusercontent.com/475462/68501551-b5e3ad80-025e-11ea-8e8b-599e1b178b55.gif)

**Comment by thorstenkampe** [comment]
`pspg` configuration file. Same for Windows and Linux
[pspgconf.txt](https://github.com/okbob/pspg/files/3825795/pspgconf.txt)

**Comment by okbob** [comment]
What is your mscli configuration?



pá 8. 11. 2019 v 19:40 odesílatel Thorsten Kampe <notifications@github.com>
napsal:

**Comment by okbob** [comment]
it looks so pspg crash when result is too small - on my terminal (gnome-terminal), there is not any problem - 
[select1.txt](https://github.com/okbob/pspg/files/3826025/select1.txt)

please, can you run pspg directly (use attached file), what do you see

pspg -f select1.txt
type select1.txt | pspg

is there still this issue?

**Comment by thorstenkampe** [comment]
Using `pspg` on its own shows no problem. The problems seems to be limited to `mssql-cli` and `litecli`. `mycli`, `pgcli`, `mysql` and `psql` show no problem.

**Comment by okbob** [comment]
pá 8. 11. 2019 v 21:46 odesílatel Thorsten Kampe <notifications@github.com>
napsal:

> Using pspg on its own shows no problem. The problems seems to be limited
> to mssql-cli and litecli. mycli, pgcli, mysql and psql show no problem.
>
please, can me send a mssql-cli config file?

**Comment by okbob** [comment]
I implemented a possibility to store some info to logfile. If you use a option `--log` and specify some file, then this file should to have content about pspg start, and some other - if it was correctly ended.

    ./pspg -f tests/pg_class.txt --log=~/pspglog
    cat ~/pspglog

What is a content of pspglog?

**Comment by thorstenkampe** [comment]
Pavel, I'm sorry for the delay in responding. You don't seem to have a Windows/Cygwin environment so let's focus on Linux. As a reminder: on Linux the screen is not cleared but the cursor travels almost to the bottom of the screen.

I was able to reproduce the issue on Linux with  `litecli --liteclirc litecli.ini sqlite.db` where litecli.ini contains
```ini
[main]
pager = pspg -F
```
*But* the issue only occurs when I run `litecli` under `GNU screen` or `tmux` - both terminal multiplexers.

**Comment by thorstenkampe** [comment]
Answering to an previous question: when I replace `pager` in `litecli`'s configuration to `pspg --version`, I get
```
/home/thorsten/data/Chinook_Sqlite.sqlite> select 1
pspg-2.5.3
with readline (version: 0x0800)
with integrated menu
ncurses version: 6.1, patch: 20190803
ncurses with wide char support
ncurses widechar num: 1
wchar_t width: 4, max: 2147483647
with postgres client integration
1 row in set
Time: 0.010s
```

**Comment by thorstenkampe** [comment]
Responding to the request for a log file when reproducing the issue:
```
 Mon Nov 11 20:44:10 2019 [68092] started
 Mon Nov 11 20:44:10 2019 [68092] read input 5 rows
 Mon Nov 11 20:44:10 2019 [68092] ncurses started
 Mon Nov 11 20:44:10 2019 [68092] screen size - maxy: 42, maxx: 160
 Mon Nov 11 20:44:10 2019 [68092] ncurses ended and quit due quit_if_one_screen option
```

**Comment by okbob** [comment]
The option `-F` does direct printing on stdout and exit. If you don't use this option, then `pspg` will be active in interactive mode every time.  The content is cleaned or scrolled up? The log line `ncurses ended and quit due quit_if_one_screen option` says - pspg printed content and correctly ended. So any cleaning should to do sql client - not pspg.

I see one possible problem - the pspg calculate with full screen size - but pgcli has four lines reserved for menu and status line and litecli maybe 7 or less. But it's strange - pspg prints 5 rows, and your terminal has 42 lines, and the content is cleaned. Now, I am sure on 99% so it is client side bug. Maybe it just doesn't support a pager possibility to just only print content without start of interactive mode.

Please, can you check so content is cleaned or scrolled?

**Comment by okbob** [comment]
I implemented new long option `--rr` where you can enter a number of reserved rows, that can be used for decision if pspg should to enter to interactive mode or not. You can use this option - for example with value 10 if it helps. I am not sure, but maybe

**Comment by thorstenkampe** [comment]
I think for the sake of clarity it's important to establish whether you can reproduce the issue. The issue on Linux shows in two ways when running `litecli` (as an example) with `pager = pspg -F`:

1. not running under `GNU screen` or `tmux` (please note that the actual result of the query is *not* shown)
```
Chinook_Sqlite.sqlite> select 1
1 row in set
Time: 0.013s
```

2. running under `GNU screen` or `tmux`
```
Chinook_Sqlite.sqlite> select 1
+---+
| 1 |
+---+
| 1 |
+---+



























1 row in set
Time: 0.011s
```
a subsequent query:
```
/home/thorsten/data/Chinook_Sqlite.sqlite> select 1
+---+
| 1 |
+---+
| 1 |
+---+


1 row in set
Time: 0.012s
```

**Comment by okbob** [comment]
út 12. 11. 2019 v 8:09 odesílatel Thorsten Kampe <notifications@github.com>
napsal:

> I think for the sake of clarity it's important to establish whether you
> can reproduce the issue. The issue on Linux shows in two ways when running
> litecli (as an example) with pager = pspg -F:
>
>    1. not running under GNU screen or tmux (please note that the actual
>    result of the query is *not* shown)
>
> Chinook_Sqlite.sqlite> select 1
> 1 row in set
> Time: 0.013s
>
>
>    1. running under GNU screen or tmux
>
> Chinook_Sqlite.sqlite> select 1
> +---+
> | 1 |
> +---+
> | 1 |
> +---+
>
>
It's strange, because pspg in this case does

    if (quit_if_one_screen)
    {
        int     available_rows = maxy;

        if (reserved_rows != -1)
            available_rows -= reserved_rows;

        /* the content can be displayed in one screen */
        if (available_rows >= desc.last_row && maxx >= desc.maxx)
        {
            LineBuffer *lnb = &desc.rows;
            int         lnb_row = 0;

            endwin();

            while (lnb_row < lnb->nrows)
                printf("%s\n", lnb->rows[lnb_row++]);

            if (logfile)
            {
                print_log_prefix(logfile);
                fprintf(logfile, "ncurses ended and quit due
quit_if_one_screen option\n");
            }

            return 0;
        }
    }

I have not a idea, what can be wrong in this code.

**Comment by okbob** [comment]
What you use a terminal type on Linux?

**Comment by okbob** [comment]
I try to reimplement -F option to be little bit more gentle - it try just display content and quit without ncurses initialization. It should to reduce some unwanted side effects. Please check it.

**Comment by thorstenkampe** [comment]
The issue is fixed on Windows/Cygwin and on Linux. Thanks a million! I'm closing this issue.

**Comment by okbob** [comment]
Thank you for report and cooperation



st 13. 11. 2019 v 23:54 odesílatel Thorsten Kampe <notifications@github.com>
napsal:
