### ISSUE TITLE
use pkg-config to find libpq

### ISSUE THREAD

**Issue by darix** [okbob/pspg#119]
pg_config is meant for server side modules not for finding client side libraries. you can use pkg-config to to find libpq instead. if you want to keep a fallback to pg_config after checking pkg-config.

**Comment by okbob** [comment]
ne 15. 12. 2019 v 7:57 odesílatel darix <notifications@github.com> napsal:

> pg_config is meant for server side modules not for finding client side
> libraries. you can use pkg-config to to find libpq instead. if you want to
> keep a fallback to pg_config after checking pkg-config.
>
how I can do it?

I try to check pkg-config on my comps, and I don't see libpq anywhere via
pkg-config.

**Comment by okbob** [comment]
ne 15. 12. 2019 v 9:02 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> ne 15. 12. 2019 v 7:57 odesílatel darix <notifications@github.com> napsal:
>
>> pg_config is meant for server side modules not for finding client side
>> libraries. you can use pkg-config to to find libpq instead. if you want to
>> keep a fallback to pg_config after checking pkg-config.
>>
> how I can do it?
>
> I try to check pkg-config on my comps, and I don't see libpq anywhere via
> pkg-config.
>

I use existing support in autoconf for libpq. If I found better script with
pkg-config support I'll replace it.

**Comment by okbob** [comment]
should be fixed now - it can do some new issues for packagers, but it is more correct.

**Comment by darix** [comment]
https://autotools.io/pkgconfig/pkg_check_modules.html
