### ISSUE TITLE
core dump using information_schema.columns and pipe

### ISSUE THREAD

**Issue by dg14** [okbob/pspg#124]
select 'select distinct '||column_name||' from prova;' from information_schema.columns where table_name='prova';
pspg: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)

Arch: ubuntu-18.04  (x86_64)
Package version: 2.6.6-1.pgdg18.04+1

**Comment by okbob** [comment]
Unfortunatelly, I am not able to repeat your issue. Please, can me send a saved text of problematic table? please, try to run 

\o file
select ...
\o

And please, attach a file.
