### ISSUE TITLE
PSPG in Ubuntu is Version: 0.9.3-1

### ISSUE THREAD

**Issue by iAmG-r00t** [okbob/pspg#125]
It lacks a lot of functionality, kindly assist in upgrading it or at least have a detailed installation guide from the source.

Ref: 
![image](https://user-images.githubusercontent.com/29776892/72952786-fce43800-3da3-11ea-8278-0614db74cb20.png)

Link: https://www.howtoinstall.me/ubuntu/18-04/pspg/

**Comment by iAmG-r00t** [comment]
and once I am able to install it from the source this happens

![image](https://user-images.githubusercontent.com/29776892/72954238-cd83fa00-3da8-11ea-9008-74837e219945.png)

Kindly assist!!

**Comment by iAmG-r00t** [comment]
Once I have been able to install it from the source this is the output I get, funnny characters in my data.

![image](https://user-images.githubusercontent.com/29776892/72954405-4f742300-3da9-11ea-968b-c9deee5f0e5d.png)

**Comment by okbob** [comment]
About upgrading - just uninstall, and install fresh version. You can compile fresh version from source code. README has part related for Debian/Ubuntu.

The screenshots shows broken UTF8 data - so there can be two issues - 1. you use ncurses (without support wide chars) lib instead ncursesw, or you environment is not good configured.

https://github.com/okbob/pspg/blob/master/README.md

You should to check system variable lang.

Please, what is a output of `pspg --version`

on my comp

[pavel@nemesis postgresql.master]$ pspg --version
pspg-2.6.6
with readline (version: 0x0800)
with integrated menu
ncurses version: 6.1, patch: 20190803
ncurses with wide char support
ncurses widechar num: 1
wchar_t width: 4, max: 2147483647

and what is a output of `set|grep LANG`

[pavel@nemesis postgresql.master]$ set | grep LANG
GDM_LANG=cs_CZ.UTF-8
LANG=cs_CZ.UTF-8

**Comment by iAmG-r00t** [comment]
Hey I tried what you told me but it never worked, for ubuntu I would advice you to edit the readme and advice people to install it from postgres repo, ubuntu repo hasn't been updated yet.

**Comment by okbob** [comment]
https://packages.ubuntu.com/search?keywords=pspg - it depends on Ubuntu version if I understand. It's common - if you have some LTS version, then use Postgres repository for fresh Postgres's packages.
