### ISSUE TITLE
Feature request: multiline content display, large texts

### ISSUE THREAD

**Issue by mbunkin** [okbob/pspg#126]
If a result contains a text field with multiple lines of content (containing line breaks), the table view breaks, pspg treats multiple lines of text as rows. Would be nice to somehow deal with it, for example, showing "\n" where a line break is (optionally highlighted to differentiate from literal \n in text), but keeping the large text in a single line.

Additionally, it would be nice to have an option to compact long texts into a reasonable width with asterisks. Sometimes you need to review the whole set of fields, and as we all know, there's no such thing as SELECT * EXCEPT longtextfield :)

**Comment by okbob** [comment]
pá 27. 3. 2020 v 16:34 odesílatel mbunkin <notifications@github.com> napsal:

> If a result contains a text field with multiple lines of content
> (containing line breaks), the table view breaks, pspg treats multiple lines
> of text as rows. Would be nice to somehow deal with it, for example,
> showing "\n" where a line break is (optionally highlighted to differentiate
> from literal \n in text), but keeping the large text in a single line.
>
> Additionally, it would be nice to have an option to compact long texts
> into a reasonable width with asterisks. Sometimes you need to review the
> whole set of fields, and as we all know, there's no such thing as SELECT *
> EXCEPT longtextfield :)
>
pspg is pager - the formatting is done on psql side. If you need break some
long lines then you can use wrapped format

\pset format wrapped
SELECT ..

Unfortunately, pspg is just pager, it only shows content prepared by psql
(or some other sql client)

Regards

Pavel

**Comment by mbunkin** [comment]
Okay, I understand. But the problem is text being wrapped by the mysql client. Since pspg is splitting the output into columns, it can track how many columns were printed before a line break, and convert it into "\n" or some other indicator of a "premature line break"?

**Comment by okbob** [comment]
pá 27. 3. 2020 v 17:55 odesílatel mbunkin <notifications@github.com> napsal:

> Okay, I understand. But the problem is text being wrapped by the mysql
> client. Since pspg is splitting the output into columns, it can track how
> many columns were printed before a line break, and convert it into "\n" or
> some other indicator of a "premature line break"?
>

you can set width of columns

\pset columns xxxx

or you can breaks lines by self. psql can format well multiline values. But
what I know the mysql client is too stupid.

postgres=# select e'ahoj\nnazdar\nbazar';
┌──────────┐
│ ?column? │
╞══════════╡
│ ahoj    ↵│
│ nazdar  ↵│
│ bazar    │
└──────────┘
(1 row)

The string literal have to be enhanced (e on start) to be \n interpreted
like \n

**Comment by jirutka** [comment]
> you can set width of columns
>
> \pset columns xxxx

This doesn’t work for me in jsonb columns. :(

**Comment by okbob** [comment]
st 5. 5. 2021 v 15:10 odesílatel Jakub Jirutka ***@***.***>
napsal:

> you can set width of columns
>
> \pset columns xxxx
>
> This doesn’t work for me in jsonb columns. :(
>

please, can you send some example?

**Comment by okbob** [comment]
st 5. 5. 2021 v 15:10 odesílatel Jakub Jirutka ***@***.***>
napsal:

> you can set width of columns
>
> \pset columns xxxx
>
> This doesn’t work for me in jsonb columns. :(
>

I tested it now, and it is working, but you should to change format first

postgres=# \pset format wrapped
Output format is wrapped.
postgres=# \pset columns 30
Target width is 30.
postgres=# select
'[1,2,3,5,6,7,8,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]'::jsonb;
┌────────────────────────────┐
│           jsonb            │
╞════════════════════════════╡
│ [1, 2, 3, 5, 6, 7, 8, 9, 0…│
│…, 0, 0, 0, 0, 0, 0, 0, 0, …│
│…0, 0, 0, 0, 0, 0, 0, 0, 0,…│
│… 0, 0, 0, 0, 0, 0, 0, 0, 0…│
│…, 0, 0, 0, 0, 0, 0, 0, 0, …│
│…0]                         │
└────────────────────────────┘
(1 row)
