### ISSUE TITLE
environment variable for pspg options

### ISSUE THREAD

**Issue by thorstenkampe** [okbob/pspg#130]
Would it be possible to implement an environment variable for pspg options - similar to `LESS` for `less`? The rationale for that would be that putting options in the `PAGER` environment variable (`PAGER='pspg -F'`) generates an error when an application tries to execute a file named "pspg -F".

**Comment by okbob** [comment]
should be done. please check in master branch.

**Comment by thorstenkampe** [comment]
The new environment variable works for options without arguments but not for `-f`:
```
pspg: option requires an argument -- f
Try /usr/local/bin/pspg --help
```
On Windows (Cygwin) `-f` is needed so `pspg` works with the `dbcli` family of sql shells.

Why does `pspg` need an option anyway to work with files? `less` can be used with stdin or a file without the need to signal (`-f`)

**Comment by okbob** [comment]
ok, it is supported now

**Comment by thorstenkampe** [comment]
I'm sorry, it does not work:
```
> PSPG='-f' pspg .bashrc
pspg: option requires an argument -- f
Try pspg --help
```

**Comment by okbob** [comment]
pá 10. 4. 2020 v 18:37 odesílatel Thorsten Kampe <notifications@github.com>
napsal:

> I'm sorry, it does not work:
>
> > PSPG='-f' pspg .bashrc
> pspg: option requires an argument -- f
> Try pspg --help
>
> -f is not necessary now, don't use it.

just

pspg file

**Comment by thorstenkampe** [comment]
Indeed, it does. Thanks a lot for continuously improving pspg.

**Comment by okbob** [comment]
thank you for tip for enhancing

Pavel

pá 10. 4. 2020 v 19:24 odesílatel Thorsten Kampe <notifications@github.com>
napsal:
