### ISSUE TITLE
When using \d the pspg pager does not open and uses normal pager instead

### ISSUE THREAD

**Issue by stephanoparaskeva** [okbob/pspg#131]
This is a really good tool, thank you!

I can't seem to get it to work for commands like \d or \dt

<img width="1061" alt="Screenshot 2020-04-17 at 16 19 07" src="https://user-images.githubusercontent.com/40718272/79585072-2e308380-80c7-11ea-925e-5b6bb006c116.png">

**Comment by okbob** [comment]
pá 17. 4. 2020 v 17:19 odesílatel Stephano Paraskeva <
notifications@github.com> napsal:

it should to work, but default behave of psql is use pager only when
content is not possible draw to display.

you can check it with

\pset pager always

\d pg_class


This is a really good tool, thank you!

**Comment by stephanoparaskeva** [comment]
@okbob  That worked, nice one !
