### ISSUE TITLE
pspg doesn't handle well unicode borders in podman container environment

### ISSUE THREAD

**Issue by praiskup** [okbob/pspg#132]
I don't know what environment setup actually causes this, but in
`$ podman run --rm -ti fedora:31 bash`.

The environment is not really extravagant:
```
HOSTNAME=
PGPORT=54321
COPR_CONFIG=/copr/copr.config
DISTTAG=f31container
PWD=/copr
container=oci
HOME=/copr
FGC=f31
TEST_REMOTE_USER=praiskup
PYTHONPATH=/copr/coprs_frontend:/copr/common
TERM=xterm
SHLVL=1
PGDATABASE=coprdb
PYTHONDONTWRITEBYTECODE=yes
PGHOST=/tmp
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
```

When I have:
```
bash-5.0$ cat ~/.psqlrc
\pset linestyle unicode
\pset border 2

-- Switch pagers with :x and :xx commands
\set x '\\setenv PAGER less'
\set xx '\\setenv PAGER \'pspg -bX --no-mouse\''
:xx
```

Then I see:
![Screenshot_20200424_092033](https://user-images.githubusercontent.com/3277839/80188428-6ed15500-8611-11ea-8c56-aa12e289d77b.png)

When I drop the `\pset border 2`, then:
```
coprdb=# select * from pg_indexes ;
malloc(): corrupted top size
```

I can live without unicode, so I didn't want to spent much time with debugging.
Let me know if I can provide some more info here.

```
$ rpm -q pspg
pspg-3.0.4-1.fc31.x86_64
```

**Comment by okbob** [comment]
pá 24. 4. 2020 v 9:57 odesílatel Pavel Raiskup <notifications@github.com>
napsal:

> I don't know what environment setup actually causes this, but in
> $ podman run --rm -ti fedora:31 bash.
>
> The environment is not really extravagant:
>
> HOSTNAME
> PGPORT=54321
> COPR_CONFIG=/copr/copr.config
> DISTTAG=f31container
> PWD=/copr
> container=oci
> HOME=/copr
> FGC=f31
> TEST_REMOTE_USER=praiskup
> PYTHONPATH=/copr/coprs_frontend:/copr/common
> TERM=xterm
> SHLVL=1
> PGDATABASE=coprdb
> PYTHONDONTWRITEBYTECODE=yes
> PGHOST=/tmp
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> _=/usr/bin/env
>
>
This looks like ncurses in 8bit mode

What is encoding of your terminal and your environment?




 When I have:
>
> bash-5.0$ cat ~/.psqlrc
> \pset linestyle unicode
> \pset border 2
>
> -- Switch pagers with :x and :xx commands
> \set x '\\setenv PAGER less'
> \set xx '\\setenv PAGER \'pspg -bX --no-mouse\''
> :xx
>
> Then I see:
> [image: Screenshot_20200424_092033]
> <https://user-images.githubusercontent.com/3277839/80188428-6ed15500-8611-11ea-8c56-aa12e289d77b.png>
>
> When I drop the \pset border 2, then:
>
> coprdb=# select * from pg_indexes ;
> malloc(): corrupted top size
>
> I can live without unicode, so I didn't want to spent much time with
> debugging.
> Let me know if I can provide some more info here.
>
> $ rpm -q pspg
> pspg-3.0.4-1.fc31.x86_64
>
>
do you see same result in psql?

\pset pager off

**Comment by okbob** [comment]
I can emulate this behave by

LC_ALL=C psql ...

What is your setting of LC_ALL?

**Comment by okbob** [comment]
I am able repeat a malloc error. Probably processing UTF8 document in C LANG environment corrupts memory :(

**Comment by praiskup** [comment]
> What is your setting of LC_ALL?

None (nor LANG or anything else), see the environment variables above.
Maybe that's the problem...

**Comment by okbob** [comment]
last commit should to fix malloc error. Please, check it. For correct displaying of utf8 chars, you should to have set LC_ALL or maybe LC_CTYPE. Or you should to disable unicode borders in psql.

**Comment by praiskup** [comment]
To what value?  Sounds a bit syntetic requirement, at least as long as
psql doesn't requires this to be set.

**Comment by okbob** [comment]
pá 24. 4. 2020 v 14:47 odesílatel Pavel Raiskup <notifications@github.com>
napsal:

> To what value? Sounds a bit synthetic requirement, at least as long as
> psql doesn't requires this to be set.
>
psql doesn't use ncurses.

you can try

LANG=C.UTF8

**Comment by praiskup** [comment]
> LANG=C.UTF8

That helps, yes.  It is just not convenient to set it explicitly.  But if
there's no sane way..  Thanks for the help!

**Comment by okbob** [comment]
so 25. 4. 2020 v 3:31 odesílatel Pavel Raiskup <notifications@github.com>
napsal:

> LANG=C.UTF8
>
> That helps, yes. It is just not convenient to set it explicitly. But if
> there's no sane way.. Thanks for the help!
>
I cannot to set this environment, and I cannot to modify a ncurses behave.
This expect correct setting

Pavel

**Comment by praiskup** [comment]
> I cannot to set this environment, and I cannot to modify a ncurses behave.

Is there some detection of the format provided by pspg?  Perhaps pspg
could modify the border format to ascii if there's no lc/lang.

**Comment by okbob** [comment]
so 25. 4. 2020 v 8:51 odesílatel Pavel Raiskup <notifications@github.com>
napsal:

> I cannot to set this environment, and I cannot to modify a ncurses behave.
>
> Is there some detection of the format provided by pspg? Perhaps pspg
> could modify the border format to ascii if there's no lc/lang.
>
pspg supports only from ascii to unicode translation. Inverse translation
is not supported by pspg and I don't plan to do it. I can fix a borders,
but I cannot to fix a content, than can contains other UTF8 chars.

More - I think so setting lc/lang is fundamental setting and it should to
fix another ncurses based applications.

Currently the strategy (everywhere what I know) is "if you know, so you can
use UTF, then use UTF", if you don't know, use 8bit encoding".

So I think if want to use correctly unicode, you should to set LC_CTYPE,
because default is 8bit
