### ISSUE TITLE
--query mode outputs first column in all output columns

### ISSUE THREAD

**Issue by df7cb** [okbob/pspg#136]
Caught by the regression tests in the Debian package:
```
$ pspg -q 'select 1 a, 2 b, 3 c' --ni
┌───┬───┬───┐
│ a │ b │ c │
├───┼───┼───┤
│ 1 │ 1 │ 1 │
└───┴───┴───┘
(1 rows)
```

**Comment by okbob** [comment]
po 25. 5. 2020 v 12:07 odesílatel Christoph Berg <notifications@github.com>
napsal:

> Caught by the regression tests in the Debian package:
>
> $ pspg -q 'select 1 a, 2 b, 3 c' --ni
>
> ┌───┬───┬───┐
>
> │ a │ b │ c │
>
> ├───┼───┼───┤
>
> │ 1 │ 1 │ 1 │
>
> └───┴───┴───┘
>
> (1 rows)
>
>
???

I don't understand

Pavel

**Comment by df7cb** [comment]
Well all I can say is that I'm getting this when building pspg from the 3.1.1 tarball.
```
$ pspg -q 'select 1, 2' --ni
┌──────────┬──────────┐
│ ?column? │ ?column? │
├──────────┼──────────┤
│        1 │        1 │
└──────────┴──────────┘
(1 rows)
```
Would the build log help?

**Comment by df7cb** [comment]
https://pgdgbuild.dus.dg-i.net/job/pspg-binaries/47/architecture=amd64,distribution=sid/console

**Comment by df7cb** [comment]
Ah, in case it wasn't clear, the bug is that the output is "1 1 1" instead of "1 2 3".

**Comment by okbob** [comment]
po 25. 5. 2020 v 12:45 odesílatel Christoph Berg <notifications@github.com>
napsal:

> Ah, in case it wasn't clear, the bug is that the output is "1 1 1" instead
> of "1 2 3".
>

this is clearly bug

I'll fix it

**Comment by okbob** [comment]
po 25. 5. 2020 v 15:25 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> po 25. 5. 2020 v 12:45 odesílatel Christoph Berg <notifications@github.com>
> napsal:
>
>> Ah, in case it wasn't clear, the bug is that the output is "1 1 1"
>> instead of "1 2 3".
>>
>
> this is clearly bug
>

should be fixed now

please, check it

Pavel

**Comment by df7cb** [comment]
Looks good now, thanks!
Will wait for the next release to update the Debian package.

**Comment by okbob** [comment]
út 26. 5. 2020 v 12:11 odesílatel Christoph Berg <notifications@github.com>
napsal:

> Looks good now, thanks!
> Will wait for the next release to update the Debian package.
>
I'll do it today evening

**Comment by okbob** [comment]
I did new release.

Pavel

út 26. 5. 2020 v 12:11 odesílatel Christoph Berg <notifications@github.com>
napsal:

**Comment by df7cb** [comment]
Everything looking perfect. Thanks!
