### ISSUE TITLE
search text not found

### ISSUE THREAD

**Issue by thorstenkampe** [okbob/pspg#138]
I have a table with a huge number of columns (264), When I search for text which is "somewhere to the right" - meaning in columns not visible - the text is not found. When I search for the same text in the transposed table (1 row x 264 col -> 264 row x 1 col) the text is found.

Is that the expected behaviour? Is there a workaround?

By the way: `less` shows the same behaviour.

**Comment by okbob** [comment]
st 27. 5. 2020 v 12:17 odesílatel Thorsten Kampe <notifications@github.com>
napsal:

> I have a table with a huge number of columns (264), When I search for text
> which is "somewhere to the right" - meaning in columns not visible - the
> text is not found. When I search for the same text in the transposed table
> (1 row x 264 col -> 264 row x 1 col) the text is found.
>
> Is that the expected behaviour? Is there a workaround?
>
No, it isn't. pspg search routine search through full line.

can me send some example?

**Comment by thorstenkampe** [comment]
@okbob you're right. The pandas dataframe was displayed truncated because of the large number of columns - which I could not see because of the large number of columns :-) .  Closing the ticket. Thanks for the support.
