### ISSUE TITLE
It is called a UNIX pager, but it is using GNU style long command line options.

### ISSUE THREAD

**Issue by qlcom** [okbob/pspg#141]
what's your opinion on that?

**Comment by okbob** [comment]
čt 27. 8. 2020 v 16:12 odesílatel qlcom <notifications@github.com> napsal:

> what's your opinion on that?
>
What do you think exactly?

pspg uses usual getopt_long function

https://linux.die.net/man/3/getopt_long

**Comment by qlcom** [comment]
it contains some GNU extension. you may the POSIX spec.

**Comment by okbob** [comment]
čt 27. 8. 2020 v 16:31 odesílatel qlcom <notifications@github.com> napsal:

> it contains some GNU extension. you may the POSIX spec.
>
It is possible, but I don't see it as problematic. Do you have some
problems with compilation on some living platforms?

**Comment by qlcom** [comment]
> Do you have some
problems with compilation on some living platforms

I haven't used this software yet.

**Comment by okbob** [comment]
Theoretically I can fix getopt_long easy, but probably there can be much more dependencies on other gcc and libc features, so I would to do these changes only when I will to have clean assignment and target. Now pspg is successfully compiled on some versions of Linux, BSD, MacOS and Solaris. The "UNIX" world in description doesn't mean so pspg is designed for UNIX certificated systems (or POSIX systems), but it so pspg is in same kind of software like UNIX pagers - less, more, ... Usually, it should be compiled on any platform where ncurses are supported well (some parts have strong dependency on libc, but it is relatively isolated and it is optional).

**Comment by okbob** [comment]
There are lot of BSD licenced implementations of getopt_long

https://github.com/libevent/libevent/blob/master/WIN32-Code/getopt_long.c
