### ISSUE TITLE
base16 theme support and/or custom themes

### ISSUE THREAD

**Issue by sebastianwebber** [okbob/pspg#142]
Hi,

How can I implement a custom theme color?

It will be super nice to use pspg with a [base16 theme](http://chriskempson.com/projects/base16/).

**Comment by okbob** [comment]
út 22. 9. 2020 v 21:37 odesílatel Sebastian Webber <notifications@github.com>
napsal:

> Hi,
>
> How can I implement a custom theme color?
>
> It will be super nice to use pspg with a base16 theme
> <http://chriskempson.com/projects/base16/>.
>
pspg doesn't support custom themes. You should to create new buildin theme.

You should to modify primary themes.c, next commands.c, commands.h, menu.c
and pspg.c .

I am waiting on pull request
