### ISSUE TITLE
How to start `pspg`

### ISSUE THREAD

**Issue by pcav** [okbob/pspg#143]
Surely I'm missing something, but I do not find in the manpage how to start the progrem. Sending `pspg` from bash the prompt stays there and I get nothing.
Sorry if this is not the right place to ask.

**Comment by okbob** [comment]
pá 25. 9. 2020 v 8:29 odesílatel Paolo Cavallini <notifications@github.com>
napsal:

> Surely I'm missing something, but I do not find in the manpage how to
> start the progrem. Sending pspg from bash the prompt stays there and I
> get nothing.
> Sorry if this is not the right place to ask.
>
pspg by default expect some result from stdin.

but if you can browse some files, then you can use a "-f" option

pspg -f xxx.csv

**Comment by pcav** [comment]
Thanks a lot, this is clear. I do not understand how this applies to postgresql tables, however.

**Comment by okbob** [comment]
pá 25. 9. 2020 v 15:02 odesílatel Paolo Cavallini <notifications@github.com>
napsal:

> Thanks a lot, this is clear. I do not understand how this applies to
> postgresql tables, however.
>

It should not be problem too

run in shell

export PAGER=pspg
psql postgres

inside psql run query "SELECT * FROM pg_class;"

exit from pager by q

**Comment by pcav** [comment]
Perfect, this is what I was missing. Thanks @okbob 
May I suggest to include these instructions in the RADME?
All the best.

**Comment by okbob** [comment]
so 26. 9. 2020 v 11:47 odesílatel Paolo Cavallini <notifications@github.com>
napsal:

> Perfect, this is what I was missing. Thanks @okbob
> <https://github.com/okbob>
>
:)

May I suggest to include these instructions in the RADME?
>
https://github.com/okbob/pspg/blob/master/README.md#recommended-psql-configuration

**Comment by pcav** [comment]
Thanks

**Comment by okbob** [comment]
:)
