### ISSUE TITLE
--help and --version returns status code 1

### ISSUE THREAD

**Issue by pmav99** [okbob/pspg#144]
Super minor nitpicks but why would `pspg --help` and `pspg --version` return 1?

```
$ pspg --version 1>/dev/null
$ echo $?
1

$ pspg --help 2>/dev/null
$ echo $?
1
```

And since we are on this topic, wouldn't it make more sense to print `--help` to STDOUT instead of STDERR? This way you could e.g. use `pspg --help | grep <foo>` or `pspg --help | less` without having to redirect the stream.

**Comment by okbob** [comment]
Should be fixed now. Thank you for report

**Comment by pmav99** [comment]
Thank you Pavel
