### ISSUE TITLE
Query result effected by pgcli named query

### ISSUE THREAD

**Issue by TThUgh** [okbob/pspg#149]
Hi,
I'm using pspg and pgcli to connect to remote DB and it's working great!
But when it comes to using named query, the output seems to be effected by the query string.
The row of the column names shift down and the first column becomes as wide as the query string.
Is there any setting that can fix this?

Thank you.

![pspg](https://user-images.githubusercontent.com/56900492/103265790-5e1b7f00-49e9-11eb-81d6-87785821dbbe.jpeg)

**Comment by okbob** [comment]
Hi

út 29. 12. 2020 v 8:42 odesílatel TThUgh <notifications@github.com> napsal:

> Hi,
> I'm using pspg and pgcli to connect to remote DB and it's working great!
> But when it comes to using named query, the output seems to be effected by
> the query string.
> The row of the column names shift down and the first column becomes as
> wide as the query string.
> Is there any setting that can fix this?
>
> [image: pspg]
> <https://user-images.githubusercontent.com/56900492/103265790-5e1b7f00-49e9-11eb-81d6-87785821dbbe.jpeg>
>
>
This is an error on the pgcli side. It is sending the query text to pager.
When you use CSV, then pgcli should produce only data to output stream
(that is redirected to pspg). But pgcli injects this CSV stream with
garbage. It should be fixed on the pgcli side. I can write only some
workaround

See commit
https://github.com/okbob/pspg/commit/650f478c03a53666528bb1579bfdc3859ab35d32

**Comment by TThUgh** [comment]
I see. And the new setting is working fine!
I'll report this to pgcli.
Thank you!

**Comment by okbob** [comment]
st 30. 12. 2020 v 4:17 odesílatel TThUgh <notifications@github.com> napsal:

> I see. And the new setting is working fine!
> I'll report this to pgcli.
> Thank you!
>

:)

Pavel
