### ISSUE TITLE
pgcli-fix option not recognized

### ISSUE THREAD

**Issue by igorkaludjer** [okbob/pspg#150]
```
pspg: unrecognized option `--pgcli-fix'
Try /opt/homebrew/bin/pspg --help
```
.pgcli config:
`pager = /opt/homebrew/bin/pspg --csv --rr=2 --quit-if-one-screen --ignore-case --csv-header on --pgcli-fix`

PSPG version:
```
pspg-3.1.5
with readline (version: 0x0800)
with integrated menu
ncurses version: 6.2, patch: 20200212
ncurses with wide char support
ncurses widechar num: 0
wchar_t width: 4, max: 2147483647
with postgres client integration
```

Python: 3.9.1 
MacOS 11.1

**Comment by okbob** [comment]
čt 31. 12. 2020 v 10:23 odesílatel Igor Kaluđer <notifications@github.com>
napsal:

> pspg: unrecognized option `--pgcli-fix'
> Try /opt/homebrew/bin/pspg --help
>
> .pgcli config:
> pager = /opt/homebrew/bin/pspg --csv --rr=2 --quit-if-one-screen
> --ignore-case --csv-header on --pgcli-fix
>
This option is two days old, and this code was not released yet.

If you want to use it, you should to build pspg from master branch

Regards

Pavel
