### ISSUE TITLE
How to activate vertical cursor mode with keyboard?

### ISSUE THREAD

**Issue by rutchkiwi** [okbob/pspg#159]
Hi! Silly question but what does M-v mean as a keyboard shortcut?

<img width="296" alt="Screenshot 2021-03-18 at 11 37 20" src="https://user-images.githubusercontent.com/512819/111612968-eda92080-87d5-11eb-97d2-b29d216d82ed.png">

**Comment by okbob** [comment]
čt 18. 3. 2021 v 11:38 odesílatel Viktor Holmberg ***@***.***>
napsal:

> Hi! Silly question but what does M-v mean as a keyboard shortcut?
>

It is ALT key on PC keyboard

Pavel

**Comment by rutchkiwi** [comment]
Thanks. Like, press ALT+v to activate vertical cursor? Doesn't work for me on mac for some reason - tried all the keys together with v and nothing works. Any ideas?

**Comment by okbob** [comment]
čt 18. 3. 2021 v 12:00 odesílatel Viktor Holmberg ***@***.***>
napsal:

> Thanks. Like, press ALT+v to activate vertical cursor? Doesn't work for me
> on mac for some reason - tried all the keys together with v and nothing
> works. Any ideas?
>

I am sure, so it should to work there, but I have not mac, so I have not
necessary knowledge.

you can try to press sequence (not together) ESC, v

**Comment by okbob** [comment]
čt 18. 3. 2021 v 12:46 odesílatel Pavel Stehule ***@***.***>
napsal:

>
>
> čt 18. 3. 2021 v 12:00 odesílatel Viktor Holmberg <
> ***@***.***> napsal:
>
>> Thanks. Like, press ALT+v to activate vertical cursor? Doesn't work for
>> me on mac for some reason - tried all the keys together with v and nothing
>> works. Any ideas?
>>
>
nobody reported me this issue, so please, can try to ask on specialized
phorums - there can be problems in terminal configuration too. But I have
not any knowledge about mac.

ESC, v should work everywhere.

Pavel

**Comment by rutchkiwi** [comment]
Ok thanks for you quick help! I'll try some tweaking to my terminal configuration.

**Comment by okbob** [comment]
maybe this hint https://www.shell-tips.com/mac/meta-key/

Pavel

čt 18. 3. 2021 v 12:51 odesílatel Pavel Stehule ***@***.***>
napsal:

**Comment by okbob** [comment]
čt 18. 3. 2021 v 13:22 odesílatel Viktor Holmberg ***@***.***>
napsal:

> Ok thanks for you quick help! I'll try some tweaking to my terminal
> configuration.
>
if you find something, tell me it - I can enhance README file

Pavel

**Comment by nielsbom** [comment]
On macOS you need to use <kbd>Esc</kbd> for the meta key (`M-`).
So showing the vertical cursor is <kbd>Esc + v</kbd>.


https://stackoverflow.com/a/71457088/61109.

@okbob do you want me to open a PR for the README with a line for this?

**Comment by okbob** [comment]
st 6. 11. 2024 v 18:06 odesílatel Niels Bom ***@***.***>
napsal:

> On macOS you need to use Esc for the meta key (M-).
> So showing the vertical cursor is Esc + v.
>
> https://stackoverflow.com/a/71457088/61109.
>
> @okbob <https://github.com/okbob> do you want me to open a PR for the
> README with a line for this?
>

please, do it
