### ISSUE TITLE
search is broken since 4.3.1 with hidden commandbar

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [okbob/pspg#164]
when the commandbar is hidden and i press `/` to search, the application hangs and fails to search anything. i can get it unstuck with `ctrl`+`c` but the search bis broken so far. i checked the latest tags and it seems to be broken since 4.3.1 up until the current master.

if i remove the `--no-commandbar` option, everything works fine.

i use it with postgresql, here are the relevant psqlrc snippets:
```
\pset format aligned
\t
\timing on
\pset footer on
\pset border 2
\pset linestyle unicode
\pset unicode_header_linestyle double
\encoding unicode

\x off
\setenv PAGER 'pspg -i -s 17 --no-mouse --no-commandbar'
```

```
$ pspg -V
pspg-4.6.0
with readline (version: 0x0801)
with integrated menu
ncurses version: 6.2, patch: 20201114
ncurses with wide char support
ncurses widechar num: 1
wchar_t width: 4, max: 2147483647
with postgres client integration
with inotify support
```

**Comment by verfriemelt-dot-org** [comment]
here it seems to be 7c97b2d which broke that functionality

**Comment by okbob** [comment]
Should be fixed by a054e47b7de292af459c581530b42eebf8731246 commit. Please, check.

**Comment by verfriemelt-dot-org** [comment]
yes perfect! :)

if you know any easy way to acceptance-test ncurses applications in an automated way, i think it would be nice to create some regression tests to check for those things. i could offer some if there would be the required infrastructure. 

really appreciate  pspg and your work!

**Comment by okbob** [comment]
st 21. 4. 2021 v 21:31 odesílatel ಠ_ಠ ***@***.***> napsal:

> yes perfect! :)
>
> if you know any easy way to acceptance-test ncurses applications in an
> automated way, i think it would be nice to create some regression tests to
> check for those things. i could offer some if there would be the required
> infrastructure.
>
Theoretically you can send to ncurses and content of any file, and you can
get other files on output. But the output content can be different in
dependency on ncurses version and on terminal type.

Regress tests can be nice, but it needs the same work like the pspg self -
and there are really a lot of combinations. So regress tests are like a
dream. I can imagine a special option that enables testing mode,  when any
state variables can be printed to stdout - instead usual content. Probably
it cannot detect some visual artefacts, but the crashes and segfaults
inside pspg can be detected well. But it is a lot of work - and I have more
other work and pspg is just my hobby project. It can be a good project for
students (but I know nobody who can do it).

On second hand - last year I did intensive development on pspg - so
probably there can be a lot of new bugs. Now, pspg has all the
functionality that I wanted to implement, and I think so now the
development will be more quiet - mostly only bug fixing, so although there
are no regress tests, the quality will be good enough.

really appreciate pspg and your work!
>

Thank you :-)

**Comment by okbob** [comment]
st 21. 4. 2021 v 22:00 odesílatel Pavel Stehule ***@***.***>
napsal:

>
>
> st 21. 4. 2021 v 21:31 odesílatel ಠ_ಠ ***@***.***> napsal:
>
>> yes perfect! :)
>>
>> if you know any easy way to acceptance-test ncurses applications in an
>> automated way, i think it would be nice to create some regression tests to
>> check for those things. i could offer some if there would be the required
>> infrastructure.
>>
> Theoretically you can send to ncurses and content of any file, and you can
> get other files on output. But the output content can be different in
> dependency on ncurses version and on terminal type.
>

ncurses has functionality that allows dump output to file - putwin. So it
is possible.  It can be good theme for diploma thesis

https://invisible-island.net/ncurses/man/curs_scr_dump.3x.html
