### ISSUE TITLE
customized null display value shows up in CSV export

### ISSUE THREAD

**Issue by dmfay** [okbob/pspg#169]
My .psqlrc contains `\pset null '(null)'`, the better to distinguish nulls from empty text values and so on:

```
$ select v, null from generate_series(0, 100) v;

  v  │ ?column? 
─────┼──────────
   0 │ (null)
   1 │ (null)
   2 │ (null)
```

But if I'm exporting results to CSV, things are a little different, and I usually want the blank space instead of the placeholder. With psql's `\copy` I get blanks as expected, but with pspg's "Save as CSV" I get this:

```
v,?column?
0,(null)
1,(null)
2,(null)
```

Since it seems like the data have already been formatted for display by the time pspg gets invoked, I don't know if there's a practical fix for this but it'd be nice to have!

**Comment by okbob** [comment]
I though about it lot of time, but I didn't find any automatic solution. On pspg side, the NULL string is unknown. pspg try to detect empty string and ∅ (null symbol) as NULL. I can implement an support for custom string entered as an pspg option, that can be used as NULL string.

**Comment by dmfay** [comment]
I didn't know it had a case for ∅! It might take a bit of getting used to but I'll try that out for a while instead of `(null)`, thanks :)

**Comment by okbob** [comment]
I pushed to master branch an possibility to specify null string. This value can is used in export.
