### ISSUE TITLE
 pspg -q "select current_timestamp"   error

### ISSUE THREAD

**Issue by cityvigil** [okbob/pspg#170]
[pg12@client1 ~]$ pspg -q "select current_timestamp" -h 127.0.0.1 -d mydb  --no-bars   -w 2
Query cannot be executed. The Postgres library was not available at compile time.
[pg12@client1 ~]$

---my os postgresql env

export PGHOME=/u01/pg12
export PGDATA=/u01/pg12_data
export PGUSER=pg12
export PGDATABASE=postgres
export LD_LIBRARY_PATH=$PGHOME/lib
export PATH=$PGHOME/bin:$PATH:.
export MANPATH=$PGHOME/share/man:$MANPATH

export TERM=xterm
export TMOUT=0

export PAGER="pspg -s 6"
[pg12@client1 ~]$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[pg12@client1 ~]$ psql
Timing is on.
Pager is always used.
psql (12.7)
Type "help" for help.

postgres=# select current_timestamp;
Time: 12.135 ms
postgres=#
postgres=# exit;

[pg12@client1 ~]$ pspg -V
pspg-4.4.0
with readline (version: 0x0602)
with integrated menu
ncurses version: 5.9, patch: 20130511
ncurses with wide char support
ncurses widechar num: 0
wchar_t width: 4, max: 2147483647
with inotify support
[pg12@client1 ~]$
[pg12@client1 ~]$
[pg12@client1 ~]$ pspg -q "select current_timestamp" -h 127.0.0.1 -d mydb  --no-bars   -w 2
Query cannot be executed. The Postgres library was not available at compile time.
[pg12@client1 ~]$

**Comment by okbob** [comment]
when you compile pspg, then you need to have libpq devel files. Without it, pspg is compiled without PostgreSQL driver, and then you cannot to use this functionality.

**Comment by okbob** [comment]
see https://github.com/okbob/pspg#note---compilation-issue

**Comment by cityvigil** [comment]
thanks .

I install pspg use  yum  install  . like  this <   yum install pspg >
