### ISSUE TITLE
Question about "Mark Column"

### ISSUE THREAD

**Issue by farzadmf** [okbob/pspg#172]
Hi,

A couple of questions:
- When I open the **Command** menu, I see **Mark column** is set to **F13**, so I was wondering what's that about, since I'm not sure if there's an F13 on the keyboard
- Also, when I mark a column and press **INS** to copy it, if the column is too long (contains a lot of characters), it seems that the value is partially copied

Can you please help?

And needless to say: thank you for the GREAT tool :+1:

**Comment by okbob** [comment]
čt 3. 6. 2021 v 19:15 odesílatel Farzad Majidfayyaz <
***@***.***> napsal:

> Hi,
>
> A couple of questions:
>
>    - When I open the *Command* menu, I see *Mark column* is set to *F13*,
>    so I was wondering what's that about, since I'm not sure if there's an F13
>    on the keyboard
>
>
This is convention - F13 is Shift F3 on keyboards without full functional
keys (probably only very old Unix keyboards had these keys)


>
>    - Also, when I mark a column and press *INS* to copy it, if the column
>    is too long (contains a lot of characters), it seems that the value is
>    partially copied
>
>

>
>
> Can you please help?
>
It is strange, there is no limit on pspg level (maybe other applications in
stack co do this)  - can you send me some test case?

And needless to say: thank you for the GREAT tool 👍
>

Thank you :)

**Comment by farzadmf** [comment]
> F13 is Shift F3

Thank you :+1: 

> keyboards without full functional keys

I didn't know the function keys could be more _full_ than 12 :laughing: 

> can you send me some test case?

Unfortunately, I can't copy/paste the data I have since it's my company's, but it's basically it's a `jsonb` in PostGres that when displayed in the terminal needs quite a few horizontal scrolls to get to the end.

I'll try to come up with an example to replicate the behavior

**Comment by okbob** [comment]
čt 3. 6. 2021 v 20:31 odesílatel Farzad Majidfayyaz <
***@***.***> napsal:

> F13 is Shift F3
>
> Thank you 👍
>
> keyboards without full functional keys
>
> I didn't know the function keys could be more *full* than 12 😆
>
> can you send me some test case?
>
> Unfortunately, I can't copy/paste the data I have since it's my company's,
> but it's basically it's a jsonb in PostGres that when displayed in the
> terminal needs quite a few horizontal scrolls to get to the end.
>
PostGres doesn't exist :) - use Postgres or PostgreSQL :)


> I'll try to come up with an example to replicate the behavior
>

sure, send me some test data, or generated data, and I'll check it

Pavel

**Comment by farzadmf** [comment]
> PostGres doesn't exist :) - use Postgres or PostgreSQL :)

Wow, good catch, and I thought I'm OCD :wink: :stuck_out_tongue_winking_eye: 

> send me some test data, or generated data

Will do for sure, thank you

**Comment by farzadmf** [comment]
Hi @okbob , so I tried to replicate the issue and this is what I have (SQL commands in Postgres - got it right this time :wink: ):
```sql
create table my(hello jsonb);
-- NOTE: a long value to make sure the pager appears
insert into my(hello) values('{"longval": "loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong"}');
insert into my(hello) values('{"myval": "hello", "val2": "hello2", "val3": "hello3"}');
```

After that, I do these:
1. `select * from my`
2. Enable vertical cursor (`M-v`)
3. Go to the row with the shorter value (the second row)
4. Mark column using the menu (question about this below :slightly_smiling_face: )
5. Press `INS` to copy to the clipboard

When I paste, I see this:
```
"{""val2"": ""hello2"", ""val3"": ""hello3"", ""myval"":
```

I hope it helps.

Also, a couple of questions:
- `SHIFT+F3` does not mark column for me and I have to go through the menu to do it. Is it possible that it's because I'm inside of `tmux`?
- Is there any way to configure `pspg` so that the quotes don't appear twice when I copy/paste?

Off the topic question:
- Is there any way to change/add key bindings? An example: `Mark all` and `Unmark` don't seem to have any bindings. Is there a way to add? Also, is there a way to change existing bindings?

Thank you for your time,
Farzad

**Comment by okbob** [comment]
I hope it helps.
>
> Also, a couple of questions:
>
>    - SHIFT+F3 does not mark column for me and I have to go through the
>    menu to do it. Is it possible that it's because I'm inside of tmux?
>
> Default setting for tmux is not good - you can try

start tmux with "-2" option,
and set sys variable TERM=xterm-256color

With this configuration Shift+F3 is working


>    - Is there any way to configure pspg so that the quotes don't appear
>    twice when I copy/paste?
>
> pspg produce csv by default - and in this format, the quotes should be
escaped

you can use INSERT format, and then you remove just INSERT VALUE keywords


>
>
> Off the topic question:
>
>    - Is there any way to change/add key bindings? An example: Mark all
>    and Unmark don't seem to have any bindings. Is there a way to add?
>    Also, is there a way to change existing bindings?
>
> There is no way - if you need it, you can modify translate_event routine
in command.c

or just use "\copy" command (you need pspg 5.0)

**Comment by okbob** [comment]
> When I paste, I see this:
> 
> ```
> "{""val2"": ""hello2"", ""val3"": ""hello3"", ""myval"":
> ```

I found an bug in csv export. Thank you for report. It should be fixed by last commit - please, check release 5.0.2

In this release you can check other export formats SQL values and pipe separated values. Maybe the last format is good for your data,

**Comment by farzadmf** [comment]
Hey @okbob , sorry for the late reply

> should be fixed by last commit

Seems to be working great in the latest version :rocket: 

However, a couple of questions about the things you mentioned:

> you can use INSERT format, and then you remove just INSERT VALUE keywords

Can you elaborate on this a bit? How do I do `INSERT` format?

> just use "\copy" command

What I'm doing is to mark the column and then do `\copy selected`, but it's also copying the borders to the clipboard. Can you please let me know what I'm missing?

**Comment by okbob** [comment]
po 7. 6. 2021 v 15:01 odesílatel Farzad Majidfayyaz <
***@***.***> napsal:

> Hey @okbob <https://github.com/okbob> , sorry for the late reply
>
> should be fixed by last commit
>
> Seems to be working great in the latest version 🚀
>
> However, a couple of questions about the things you mentioned:
>
> you can use INSERT format, and then you remove just INSERT VALUE keywords
>
> Can you elaborate on this a bit? How do I do INSERT format?
>
> just use "\copy" command
>
> What I'm doing is to mark the column and then do \copy selected, but it's
> also copying the borders to the clipboard. Can you please let me know what
> I'm missing?
>
pspg supports some exported formats - last week I wrote two new - sqlvalues
and pipe separated

you should to specify format

\copy selected sqlvalues
or

\copy selected pipesep

**Comment by farzadmf** [comment]
Thank you so much @okbob for your super quick responses and taking care of this. I'm going to close the issue now because as far as I'm concerned, it's solved.

Will bother you with more questions if they come up :wink:

**Comment by okbob** [comment]
út 8. 6. 2021 v 3:38 odesílatel Farzad Majidfayyaz ***@***.***>
napsal:

> Thank you so much @okbob <https://github.com/okbob> for your super quick
> responses and taking care of this. I'm going to close the issue now because
> as far as I'm concerned, it's solved.
>
> Will bother you with more questions if they come up 😉
>

ook :)
