### ISSUE TITLE
5.0.2 fails to build on RHEL 7

### ISSUE THREAD

**Issue by devrimgunduz** [okbob/pspg#174]
Hi,

5.0.2 fails to build on RHEL 7, gcc 4.8.5. Can you please take a look? Thanks! Devrim

`gcc  -c src/menu.c -o menu.o  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -I/usr/include/ncurses/ -DCOMPILE_MENU     -DPACKAGE_NAME=\"pspg\" -DPACKAGE_TARNAME=\"pspg\" -DPACKAGE_VERSION=\"0\" -DPACKAGE_STRING=\"pspg\ 0\" -DPACKAGE_BUGREPORT=\"pavel.stehule@gmail.com\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DGWINSZ_IN_SYS_IOCTL=1 -DHAVE_NCURSESW=1 -DHAVE_CURSES=1 -DHAVE_CURSES_ENHANCED=1 -DHAVE_CURSES_COLOR=1 -DHAVE_CURSES_OBSOLETE=1 -DHAVE_NCURSESW_CURSES_H=1 -DHAVE_CURSES_ENHANCED=1 -DHAVE_CURSES_COLOR=1 -DHAVE_CURSES_OBSOLETE=1 -DHAVE_NCURSES_H=1 -DHAVE_PANEL=1 -DHAVE_NCURSESW_PANEL_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIBREADLINE=1 -DHAVE_READLINE_READLINE_H=1 -DHAVE_READLINE_HISTORY=1 -DHAVE_READLINE_HISTORY_H=1 -DHAVE_POSTGRESQL=1 -DHAVE_LIBM=1 -DHAVE_SYS_INOTIFY_H=1 -DHAVE_INOTIFY=1 -Wall -MD
src/st_menu.c: In function 'chr_casexfrm':
src/st_menu.c:299:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   *((int *) buffer) = fold;
   ^
gcc  csv.o print.o commands.o unicode.o themes.o pspg.o config.o sort.o pgclient.o args.o infra.o file.o table.o string.o export.o linebuffer.o st_menu.o st_menu_styles.o menu.o -o pspg -Wl,-z,relro  -lm  -lreadline -lpanelw -lncursesw     -lpq  
pspg.o: In function `get_event':
/var/lib/pgsql/rpmcommon/BUILD/pspg-5.0.2/src/pspg.c:1827: undefined reference to `wgetdelay'
pspg.o: In function `export_to_file':
/var/lib/pgsql/rpmcommon/BUILD/pspg-5.0.2/src/pspg.c:2491: undefined reference to `wgetdelay'
collect2: error: ld returned 1 exit status
make[1]: *** [pspg] Error 1
`

**Comment by okbob** [comment]
Hi 

last commit should to fix it. Please, check it.

**Comment by okbob** [comment]
Hi @devrimgunduz, 

please, can you check the build?

**Comment by devrimgunduz** [comment]
Hi @okbob,

Sorry for the delay. 5.0.4 builds fine.

Regards, Devrim

**Comment by okbob** [comment]
po 21. 6. 2021 v 20:39 odesílatel Devrim Gündüz ***@***.***>
napsal:

> Hi @okbob <https://github.com/okbob>,
>
> Sorry for the delay. 5.0.4 builds fine.
>

super, thank you for confirm

Pavel

Regards, Devrim
