### ISSUE TITLE
5.0.5 does not build on RHEL 7

### ISSUE THREAD

**Issue by devrimgunduz** [okbob/pspg#179]
Hi @okbob ,

5.0.5 fails to build on RHEL 7. We had a similar problem in https://github.com/okbob/pspg/issues/174 . Can you please take a look? Thanks!

> gcc  -c src/menu.c -o menu.o  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -I/usr/include/ncurses/ -DCOMPILE_MENU     -DPACKAGE_NAME=\"pspg\" -DPACKAGE_TARNAME=\"pspg\" -DPACKAGE_VERSION=\"0\" -DPACKAGE_STRING=\"pspg\ 0\" -DPACKAGE_BUGREPORT=\"pavel.stehule@gmail.com\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DGWINSZ_IN_SYS_IOCTL=1 -DHAVE_NCURSESW=1 -DHAVE_CURSES=1 -DHAVE_CURSES_ENHANCED=1 -DHAVE_CURSES_COLOR=1 -DHAVE_CURSES_OBSOLETE=1 -DHAVE_NCURSESW_CURSES_H=1 -DHAVE_CURSES_ENHANCED=1 -DHAVE_CURSES_COLOR=1 -DHAVE_CURSES_OBSOLETE=1 -DHAVE_NCURSES_H=1 -DHAVE_PANEL=1 -DHAVE_NCURSESW_PANEL_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIBREADLINE=1 -DHAVE_READLINE_READLINE_H=1 -DHAVE_READLINE_HISTORY=1 -DHAVE_READLINE_HISTORY_H=1 -DHAVE_POSTGRESQL=1 -DHAVE_LIBM=1 -DHAVE_SYS_INOTIFY_H=1 -DHAVE_INOTIFY=1 -Wall -MD
src/readline.c: In function 'pspg_save_history':
src/readline.c:124:2: warning: implicit declaration of function 'rl_clear_history' [-Wimplicit-function-declaration]
  rl_clear_history();
  ^
gcc  csv.o print.o commands.o unicode.o themes.o pspg.o config.o sort.o pgclient.o args.o infra.o file.o table.o string.o export.o linebuffer.o bscommands.o readline.o st_menu.o st_menu_styles.o menu.o -o pspg -Wl,-z,relro  -lm  -lreadline -lpanelw -lncursesw     -lpq  
readline.o: In function `pspg_save_history':
/var/lib/pgsql/rpmcommon/BUILD/pspg-5.0.5/src/readline.c:124: undefined reference to `rl_clear_history'
collect2: error: ld returned 1 exit status
make[1]: *** [pspg] Error 1
make[1]: Leaving directory `/home/pgsql/rpmcommo

**Comment by okbob** [comment]
should be fixed in 5.1.0.

**Comment by okbob** [comment]
Immediately after release I found an new bug related to using nonl mode. I fixed it in 5.1.1 release
