### ISSUE TITLE
Yet another RHEL 7 build issue

### ISSUE THREAD

**Issue by devrimgunduz-edb** [okbob/pspg#182]
Hi @okbob ,

5.3.1 failst to build on RHEL 7:

src/print.c: In function 'window_fill':
src/print.c:1324:20: error: 'A_ITALIC' undeclared (first use in this function)
new_attr |= A_ITALIC | A_UNDERLINE;
^
src/print.c:1324:20: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [print.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/pgsql/rpmcommon/BUILD/pspg-5.3.1'
error: Bad exit status from /var/tmp/rpm-tmp.t4FHiX (%build)

**Comment by devrimgunduz-edb** [comment]
Thanks! Pushed to repos.

Cheers, Devrim

**Comment by okbob** [comment]
Thank you

Pavel

st 4. 8. 2021 v 15:51 odesílatel devrimgunduz-edb ***@***.***>
napsal:
