### ISSUE TITLE
v5.3.3 stopped working with SQLite?

### ISSUE THREAD

**Issue by loveencounterflow** [okbob/pspg#183]
hi there, I just upgraded to v5.3.3 by doing `brew install pspg` on Linux Mint 19.3; I think before I had v5.0.3. Unfortunately now when I do 

```bash
sqlite3 -csv -header ':memory:' "select 42 as a, 105 as b, 'helo' as c;" | pspg -s6 --csv --csv-header=on --double-header
```

I get a screen that is empty except for the chrome. I can leave out the `--csv` switch but then of course `pspg` treats the output as lines of text.

I do have

```
.headers on
.mode table
.nullvalue '∎'
```

in my `~/.sqliterc` but deleting those entries doesn't change the outcome. **EDIT** The issue does not seem to be related to SQLite in any way anyhow because I can `cat file.csv | pspg` and the output disappears as above when I add the `--csv` switch.

**Comment by loveencounterflow** [comment]
**UPDATE** Bifurcation results

I downloaded the source for a few versions, compiled them with `./configure && ./autogen.sh && make` and ran them with

```bash
sqlite3 -csv -header ':memory:' "select 42 as a, 105 as b, 'helo' as c;" | /tmp/pspg/pspg-X.X.X/pspg -s6 --csv --csv-header=on --double-header
```

here are the results:
* `pspg-5.3.0`—not ok
* `pspg-5.2.0`—**not ok**
* `pspg-5.1.3`—**ok**
* `pspg-5.1.0`—ok
* `pspg-5.0.1`—ok

So it would look like the bug (if any) was introduced in v5.2.0...

**Comment by okbob** [comment]
čt 12. 8. 2021 v 11:04 odesílatel loveencounterflow <
***@***.***> napsal:

> *UPDATE* Bifurcation results
>
> I downloaded the source for a few versions, compiled them with ./configure
> && ./autogen.sh && make and ran them with
>
> sqlite3 -csv -header ':memory:' "select 42 as a, 105 as b, 'helo' as c;" | /tmp/pspg/pspg-X.X.X/pspg -s6 --csv --csv-header=on --double-header
>
> here are the results:
>
>    - pspg-5.3.0—not ok
>    - pspg-5.2.0—*not ok*
>    - pspg-5.1.3—*ok*
>    - pspg-5.1.0—ok
>    - pspg-5.0.1—ok
>
> So it would look like the bug (if any) was introduced in v5.2.0...
>
yes,  it is pspg bug. Import csv is still supported, although it looks be
broken now. I'll check it

**Comment by loveencounterflow** [comment]
thanks, looking forward to that :-)

**Comment by okbob** [comment]
I hope, so I fixed this issue. Please, check 5.3.4

**Comment by loveencounterflow** [comment]
It works! Thanks a bunch for your work (and sorry it took me so long to get back to you, busy times over here). Cheers!

**Comment by okbob** [comment]
ne 15. 8. 2021 v 16:34 odesílatel loveencounterflow <
***@***.***> napsal:

> It works! Thanks a bunch for your work (and sorry it took me so long to
> get back to you, busy times over here). Cheers!
>
no problem, thank you for report

Pavel
