### ISSUE TITLE
Incorrect colors, and invisible text

### ISSUE THREAD

**Issue by padhia** [okbob/pspg#184]
Hi,

Sorry if there is an obvious solution out there, but I haven't been able to get `pspg` to display text and/or colors correctly. I am using `pspg 5.3.2` using Arch AUR on Manjaro Linux, KDE with Konsole, and Alacritty terminals. I have `TERM=xterm-256color`. With the default theme (Midnight-black), the screen is entirely dark with no text visible except for bands of light colors for the status and menu. Moving up/down using cursor keys does change the line # and %, so I know data is being read. I tried other themes, but generally, I just see two (incorrect) colors. The only text that is legible is the status information in the top right corner and bottom row function key labels. Have I misconfigured something?

**Comment by okbob** [comment]
ne 15. 8. 2021 v 14:46 odesílatel padhia ***@***.***> napsal:

> Hi,
>
> Sorry if there is an obvious solution out there, but I haven't been able
> to get pspg to display text and/or colors correctly. I am using pspg 5.3.2
> using Arch AUR on Manjaro Linux, KDE with Konsole, and Alacritty terminals.
> I have TERM=xterm-256color. With the default theme (Midnight-black), the
> screen is entirely dark with no text visible except for bands of light
> colors for the status and menu. Moving up/down using cursor keys does
> change the line # and %, so I know data is being read. I tried other
> themes, but generally, I just see two (incorrect) colors. The only text
> that is legible is the status information in the top right corner and
> bottom row function key labels. Have I misconfigured something?
>
This is strange - it looks like some terminal setting on your side is
broken. pspg for basic themes uses just basic ncurses features and nothing
else. In mc-black theme it uses default colors - defined by the terminal
emulator application.

Maybe konsole doesn't work well with TERM=xterm-256color (I see bad colors
when I use konsole and hicolor themes). You can try to change

export TERM=konsole
export TERM=konsole-256color
export TERM=xterm
export TERM=xterm-color

The terminal base is included inside ncurses. Maybe your ncurses
installation is broken. I tested Alacritty and it is working without any
problem (with hi color themes too).

You can try to check profile in console - there is color setting - I use
"linux colors"

You can check if your terminfo database has xterm-256color

find /usr/share/terminfo -type f

**Comment by padhia** [comment]
Thank you for the quick response and the tips. What helped was, upgrading to the latest version `pspg 5.3.4`. Generally, Arch and AUR are pretty good at updating to the latest versions, but I didn't think using [AUR](https://aur.archlinux.org/packages/pspg/) which is 2 patch versions behind would make much difference. I should have also mentioned that I was primarily testing CSV files. Your release comments for `5.3.4` prompted me to build the latest version by hand, and that seemed to have fixed the problem. 

Again, thank you for creating `pspg` and providing quick support.

**Comment by okbob** [comment]
ne 15. 8. 2021 v 20:36 odesílatel padhia ***@***.***> napsal:

> Thank you for the quick response and the tips. What helped was, upgrading
> to the latest version pspg 5.3.4. Generally, Arch and AUR are pretty good
> at updating to the latest versions, but I didn't think using AUR
> <https://aur.archlinux.org/packages/pspg/> which is 2 patch versions
> behind would make much difference. I should have also mentioned that I was
> primarily testing CSV files. Your release comments for 5.3.4 prompted me
> to build the latest version by hand, and that seemed to have fixed the
> problem.
>
aha - I didn't understand so you used a CSV file. So the mystery is solved
:). I did significant change in 5.2.0 - unfortunately I broke CSV. Last
week I got an error report about it, and I fixed it.


> Again, thank you for creating pspg and providing quick support.
>

:-) Thank you

Pavel
