### ISSUE TITLE
macOS Support for File Streams

### ISSUE THREAD

**Issue by rwbaskette** [okbob/pspg#187]
Hello and thank you for this amazing tool!

I was wondering if you'd consider implementing macOS compatibly fsevents so we can use native macOS builds with streaming results.

As of right now starting a stream on the latest macOS11 yields the inotify check error:

```streaming on file is not available without file notification service```

I may be able to lend a hand if you can point me in the right direction.

Thank You!

**Comment by okbob** [comment]
I didn't test it, but streaming over named pipe should to work on macOS too. But implementing support for working with usual file should not be hard too. Everywhere where in pspg code is used `#ifdef HAVE_INOTIFY`, then somebody needs to write support for `kqueue`. It is mainly `inputs.c` file. I think so it can be about 200 lines +/-.

This can be nice feature - for users on macOS or BSD. But I have not macOS, and I don't use BSD, so I cannot to verify an functionality. If you can do it, it can be nice.

**Comment by okbob** [comment]
should be fixed by 6f69632662c7be5c926affdc8b94615d6aef1223. I have not macOS, so I cannot to check it on this platform. But it is working on FreeBSD, so I hope so it can work on macOS too.

**Comment by rwbaskette** [comment]
Thanks! I have not had time to dig in and add it, but I sure will test it!
