### ISSUE TITLE
kqueue on OpenBSD

### ISSUE THREAD

**Issue by omar-polo** [okbob/pspg#195]
Hello,

I'm unable to build the latest release on OpenBSD because NOTE_CLOSE_WRITE is not defined here.  For the record, [these are the supported events](https://man.openbsd.org/kqueue#EVFILT_VNODE), and from what I see [darwin also lacks those NOTE_CLOSE* events](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/kqueue.2.html).

With the kqueue disabled (by commenting the check in configure.ac) then it builds and runs fine.

**Comment by okbob** [comment]
st 3. 11. 2021 v 12:21 odesílatel omar-polo ***@***.***>
napsal:

> Hello,
>
> I'm unable to build the latest release on OpenBSD because NOTE_CLOSE_WRITE
> is not defined here. For the record, these are the supported events
> <https://man.openbsd.org/kqueue#EVFILT_VNODE>, and from what I see darwin
> also lacks those NOTE_CLOSE* events
> <https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/kqueue.2.html>
> .
>
Is there some alternative?

**Comment by omar-polo** [comment]
Well, you know the codebase better than me, but I tried to drop the whole NOTE_CLOSE_WRITE check and pspg seems to work just as fine.

IIUC, the NOTE_CLOSE_WRITE is used to close the stream, something that the main already does during the shutdown of the program, so I guess is safe to drop.  I tried with both viewing a CSV file and as psql pager.

```patch
diff --git a/src/inputs.c b/src/inputs.c
index 4874d1a..063199f 100644
--- a/src/inputs.c
+++ b/src/inputs.c
@@ -436,7 +436,6 @@ repeat_reading:
 					{
 						struct kevent kqev;
 						struct timespec tmout = {0, 0};
-						bool		stream_closed = false;
 						int			rc;
 
 						rc = kevent(notify_fd, NULL, 0, &kqev, 1, &tmout);
@@ -444,8 +443,6 @@ repeat_reading:
 						{
 							if (kqev.flags & EV_ERROR)
 								log_row("kqueue EV_ERROR (%s)", strerror(kqev.data));
-							else if (kqev.flags & NOTE_CLOSE_WRITE)
-								stream_closed = true;
 
 							rc = kevent(notify_fd, NULL, 0, &kqev, 1, &tmout);
 						}
@@ -453,13 +450,7 @@ repeat_reading:
 						if (rc == -1)
 							log_row("kqueue error (%s)", strerror(errno));
 
-						if (stream_closed)
-						{
-							log_row("detected CLOSE WRITE by kqueue");
-							close_data_stream();
-						}
-
-						usleep(1000 * (stream_closed ? 100 : 250));
+						usleep(1000 * 250);
 					}
 
 #endif
@@ -738,7 +729,6 @@ open_data_stream(Options *opts)
 			EV_SET(&event,
 				   fileno(f_data),
 				   EVFILT_VNODE, EV_ADD | EV_ENABLE | EV_CLEAR,
-				   NOTE_CLOSE_WRITE |
 				   (current_state->stream_mode ? NOTE_WRITE : 0),
 				   0, NULL);
 

```

I can turn this into a PR if it seems fine to you.

Thanks :)

**Comment by okbob** [comment]
When you drop these events, then you block automatic refresh after file was changed. I can block these events on platforms where it is not supported. The automatic refresh is very specific functionality, and probably people can live without it (it was supported only on Linux)

**Comment by omar-polo** [comment]
I didn't noticed that, apologies.  But then I don't understand how `NOTE_CLOSE_WRITE` helps with that.  Shouldn't NOTE_WRITE/EXTEND/DELETE/TRUNCATE/RENAME provide a better indication?

Anyway, refreshing the file after a change seems a useful feature, I'll try to see if I can make it work.  Just to be sure: opening a CSV file with `pspg data.csv` and then editing the CSV file should make pspg re-read it, right?

**Comment by okbob** [comment]
čt 4. 11. 2021 v 20:27 odesílatel omar-polo ***@***.***>
napsal:

> I didn't noticed that, apologies. But then I don't understand how
> NOTE_CLOSE_WRITE helps with that. Shouldn't
> NOTE_WRITE/EXTEND/DELETE/TRUNCATE/RENAME provide a better indication?
>
> Anyway, refreshing the file after a change seems a useful feature, I'll
> try to see if I can make it work. Just to be sure: opening a CSV file with pspg
> data.csv and then editing the CSV file should make pspg re-read it, right?
>
yes

I need to detect the CLOSE_WRITE event, because only at this moment I am
sure the input file is complete. I use NOTE_WRITE for streaming mode - in
this mode, I am able to detect not complete input, and I can wait for other
data, but it is relatively fragile, because input formats are not strongly
structured. Processing the CLOSE_WRITE event is much more simple. In this
case I can expect a completed input file.

Please can you check commit 8a88c4215a5083cc6dabed6e8ebc1bf3ec38c65b if
build on OpenBSD is fixed?

**Comment by omar-polo** [comment]
Yep, the latest master builds and runs fine on OpenBSD too, without the auto refresh.  Thanks! :)

**Comment by okbob** [comment]
čt 4. 11. 2021 v 23:44 odesílatel omar-polo ***@***.***>
napsal:

> Yep, the latest master builds and runs fine on OpenBSD too, without the
> auto refresh. Thanks! :
>
I made some changes. Please, can you recheck it again?

**Comment by omar-polo** [comment]
Hi!

It still builds fine and works on OpenBSD, and as before external changes to the same file don't trigger an auto refresh.

Thanks!

**Comment by okbob** [comment]
pá 5. 11. 2021 v 8:34 odesílatel omar-polo ***@***.***>
napsal:

> Hi!
>
> It still builds fine and works on OpenBSD, and as before external changes
> to the same file don't trigger an auto refresh.
>

thank you for check

Pavel

Thanks!

**Comment by omar-polo** [comment]
Thanks for promptly looking into this issue! :)
