### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by janlimpens** [okbob/pspg#199]
On longer result sets I am consistently getting:
```
> select * from xxx;
pspg crashed by signal 11
Segmentation fault (core dumped)
Time: 2.984 ms
```
after scrolling quite a few pages down
if odd line coloring is on

5.5.2 on debian sid
installed via linux brew

**Comment by okbob** [comment]
Is it related to 5.5.2 release only?

What is longer result? Can you send me example of data where pspg fails? Can you find this query against system tables?

**Comment by janlimpens** [comment]
I just found out it has to do with coloring odd lines. Once I set this to off, no more crashes. While this fixes it for me, you may want to have a look into it. Great software, by the way! Kudos!!!

**Comment by janlimpens** [comment]
I had it in both 5.5.1 and 5.5.2

**Comment by okbob** [comment]
yes, now I was able to reproduce it. I'll fix. Thank you for report

**Comment by okbob** [comment]
Should be fixed in 5.5.3 (master). Please, test it.

**Comment by janlimpens** [comment]
a bit late, but just to confirm, it's been fixed.

**Comment by okbob** [comment]
Thank you for check :)

út 21. 12. 2021 v 15:04 odesílatel Jan ***@***.***> napsal:
