### ISSUE TITLE
CSV-only build

### ISSUE THREAD

**Issue by slackwhere** [okbob/pspg#203]
I frequently use pspg to view CSV files, this is a great feature. If It attempt to build it on a system without PGSQL or MYSQL installed the configure script terminates with the following error.

> 
> checking for the PostgreSQL libraries CPPFLAGS... Package libpq was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libpq.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libpq' found

Is it possible to build it as a simple CSV viewer and not require linking with database libraries? If not, that would be a nice enhancement.

**Comment by okbob** [comment]
so 23. 7. 2022 v 16:58 odesílatel slackwhere ***@***.***>
napsal:

> I frequently use pspg to view CSV files, this is a great feature. If It
> attempt to build it on a system without PGSQL or MYSQL installed the
> configure script terminates with the following error.
>
> checking for the PostgreSQL libraries CPPFLAGS... Package libpq was not
> found in the pkg-config search path.
> Perhaps you should add the directory containing `libpq.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libpq' found
>
> Is it possible to build it as a simple CSV viewer and not require linking
> with database libraries? If not, that would be a nice enhancement.
>

The dependency on libpq is optional.

checking for readline.h... no
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
checking whether readline supports history... yes
checking history.h usability... no
checking history.h presence... no
checking for history.h... no
checking readline/history.h usability... yes
checking readline/history.h presence... yes
checking for readline/history.h... yes
checking for gawk... gawk
checking for pkg-config... (cached) /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for the PostgreSQL libraries CPPFLAGS... Package libpq was not
found in the pkg-config search path.
Perhaps you should add the directory containing `libpq.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpq', required by 'virtual:world', not found

checking for the pg_config program...
configure: PostgreSQL library not found
checking for roundl in -lm... yes
checking for library containing clock_gettime... none required
checking sys/inotify.h usability... yes
checking sys/inotify.h presence... yes
checking for sys/inotify.h... yes
checking sys/event.h usability... no
checking sys/event.h presence... no
checking for sys/event.h... no
configure: creating ./config.status
config.status: creating config.make

and just run make - in this case pspg will be compiled without possibility
to be used as psql client (directly connected to database)

**Comment by slackwhere** [comment]
LOL, I wish I had tried that before raising an issue. Indeed you are correct, that works great. Is that documented in the README and perhaps I just missed it?

Thank you again for making this excellent software available!

**Comment by okbob** [comment]
so 23. 7. 2022 v 18:55 odesílatel slackwhere ***@***.***>
napsal:

> LOL, I wish I had tried that before raising an issue. Indeed you are
> correct, that works great. Is that documented in the README and perhaps I
> just missed it?
>
probably it is not documented - I didn't think this is extra important,
today almost all people use installation from packages.

and who do their own build, then usually just try it :)


> Thank you again for making this excellent software available!
>
:)

Regards

Pavel
