### ISSUE TITLE
Question: How does "Upper case sentitive search work"?

### ISSUE THREAD

**Issue by slackwhere** [okbob/pspg#205]
Case sensitive and case insensitive work as I would expect. When I use "Upper case sensitive search" no matches are ever found if the search string contains any upper case characters. There must be something I don't understand about how this search method works.

**Comment by okbob** [comment]
so 30. 7. 2022 v 16:02 odesílatel slackwhere ***@***.***>
napsal:

> Case sensitive and case insensitive work as I would expect. When I use
> "Upper case sensitive search" no matches are ever found if the search
> string contains any upper case characters. There must be something I don't
> understand about how this search method works.
>
/*
 * Special string searching, lower chars are case insensitive,
 * upper chars are case sensitive.
 */

so if you are searching string Hello, then you can find the strings Hello
or HELLO, but you cannot to find string hello

But when I tested it now, it doesn't work, so maybe there is some bug

**Comment by okbob** [comment]
There was a bug. It should be fixed by commit ab0950b99597d615edba0c19d612975c8e27649c . Please, check.

**Comment by slackwhere** [comment]
I can confirm it is now working.

Thank you!!

**Comment by okbob** [comment]
ne 31. 7. 2022 v 15:52 odesílatel slackwhere ***@***.***>
napsal:

> I can confirm it is now working.
>
> Thank you!!
>

:-)

Thank you for bug report

Pavel
