### ISSUE TITLE
Man pages?

### ISSUE THREAD

**Issue by symgryph** [okbob/pspg#206]
I noticed that there don't seem to be any man pages? Markdown? I like to have man pages. Great tool!

Thomas

**Comment by okbob** [comment]
Hi

pá 19. 8. 2022 v 6:06 odesílatel Thomas ***@***.***> napsal:

> I noticed that there don't seem to be any man pages? Markdown? I like to
> have man pages. Great tool!
>
I did extra man page pspg.1 from README file

pspg is github project and the README is more usual there, and I am not
expert for creating and maintaining man pages

Regards

Pavel
