### ISSUE TITLE
Erase bottom line at exit

### ISSUE THREAD

**Issue by Ximalas** [okbob/pspg#208]
It would be better if pspg can erase the bottom line of the terminal when exiting.

**Comment by okbob** [comment]
Can you describe more your idea? I am using pspg years from psql and I hadn't like this necessity. 

How do you use pspg?

**Comment by Ximalas** [comment]
I run pspg from within psql, and to me it looks cleaner if the bottom line isn't a mix of the psql command prompt and the key hint bar when I exit pspg.

**Comment by okbob** [comment]
po 3. 10. 2022 v 18:19 odesílatel Ximalas ***@***.***> napsal:

> I run pspg from within psql, and to me it looks cleaner if the bottom line
> isn't a mix of the psql command prompt and the key hint bar when I exit
> pspg.
>
on my terminal pspg doesn't do this. Can you send screenshots? On my
screenshots you can see the screen after leaving pspg, and there are not
any key hints.

What is your platform? What is your terminal? I remember that some BSD
platforms don't correctly implement alternate screen in terminals.

**Comment by Ximalas** [comment]
I'm using FreeBSD current, MATE, Alacritty, and screen. See https://ximalas.info/~trond/pspg/pspg-001.png.

**Comment by okbob** [comment]
po 3. 10. 2022 v 20:29 odesílatel Ximalas ***@***.***> napsal:

> I'm using FreeBSD current, MATE, Alacritty, and screen. See
> https://ximalas.info/~trond/pspg/pspg-001.png.
>
Yes, I thought so.

https://unix.stackexchange.com/questions/235635/alternate-screen-on-freebsds-sc-and-vt

Maybe I will write some workarounds. Unfortunately, I am not BSD user, and
I don't know usual design for this issue.

As workaround you can use option -X for pspg

export PSQL_PAGER="pspg -X"
psql

It is not without unwanted visual artefacts, but it is better than without
it (I think)

**Comment by Ximalas** [comment]
Actually, -X isn't that bad. Yes, it strips off the colours when I hit the q key, but the bottom line is erased before psql displays its command prompt.

**Comment by okbob** [comment]
now you can use options --at-end-clean, --at-end-reset and --at-end-erase-line.

please, check

**Comment by Ximalas** [comment]
I tried --at-end-erase-line and it's perfect. There is a typo for --at-end-erase-line in the help text, args.c, line 381. https://github.com/okbob/pspg/blob/master/src/args.c#L381

**Comment by Ximalas** [comment]
Maybe saying at exit is better than saying at end.

**Comment by okbob** [comment]
st 5. 10. 2022 v 19:19 odesílatel Ximalas ***@***.***> napsal:

> I tried --at-end-erase-line and it's perfect. There is a typo for
> --at-end-erase-line in the help text, args.c, line 381.
> https://github.com/okbob/pspg/blob/master/src/args.c#L381
>

should be fixed now

**Comment by okbob** [comment]
st 5. 10. 2022 v 19:21 odesílatel Ximalas ***@***.***> napsal:

> Maybe saying at exit is better than saying at end.
>

good idea. I renamed these options to --on-exit-xxx

**Comment by Ximalas** [comment]
This looks good to me. I hope others find this as a useful change.

**Comment by okbob** [comment]
st 5. 10. 2022 v 20:31 odesílatel Ximalas ***@***.***> napsal:

> This looks good to me. I hope others find this as a useful change.
>
yes  :-)

It can fix unwanted behave on some platforms
