### ISSUE TITLE
Some styles cause shell styles to break

### ISSUE THREAD

**Issue by dark-panda** [okbob/pspg#211]
Styles 17, 18, 19, 20, and 21 cause shell styles to sort of carry on their styling even after the pspg process exits. In my shell, I have the `ls` command aliased to `ls --color=auto`, and after using pspg with any of these themes, the colours for my shell persist even after pspg exits.

Here's how my shell should look:

![Screen Shot 2022-11-08 at 11 13 35 AM](https://user-images.githubusercontent.com/84783/200603739-a1cb95eb-3558-456d-8373-a19c6094f443.png)

Here's how it looks when you use any of the affected styles, with only the colours varying between styles:

![Screen Shot 2022-11-08 at 11 13 50 AM](https://user-images.githubusercontent.com/84783/200604012-5467b610-d48d-411f-93c9-a918a3f7fe8a.png)

The colours on the directories for instance are incorrect after running the pspg command with style 17.

**Comment by okbob** [comment]
What is your platform? What version of ncurses do you use? I cannot to reproduce on my FC36.

Can you check the commit https://github.com/okbob/pspg/commit/f9ff69f0160a1bc16da8dcb9be59ddc6096d855c ?

**Comment by dark-panda** [comment]
Platform: macOS 12.6
Shell: zsh 5.9
Terminal: iterm2 3.4.16
ncurses version: 6.3

The issue still appears with this commit. I've poked around a bit though, and it appears to be connected with calls to `deftheme_rgb`, as commenting out the code in that function specifically appears to work.

**Comment by okbob** [comment]
Please can you try this workaround - https://github.com/okbob/pspg/commit/70d3f388f08fd034e2e8fb5633508b42ba449d0f ?

What is an output, when you run pspg (with this commit) with an argument `--version` ?

Unfortunately, In terminals I cannot to save current state of colours and I cannot to revert to some state. I don't have macos, so I a not able to reproduce this issue. You can try to use an option `--on-exit-reset` too, Maybe it can help.

**Comment by okbob** [comment]
please, can you check last workaround?

**Comment by dark-panda** [comment]
@okbob Still appears to have the issue. The `--on-exit-reset` option does indeed clear up the issue, however.

**Comment by okbob** [comment]
út 22. 11. 2022 v 16:55 odesílatel J ***@***.***> napsal:

> @okbob <https://github.com/okbob> Still appears to have the issue. The
> --on-exit-reset option does indeed clear up the issue, however.
>
Unfortunately, I cannot fix it (it is out of my possibilities when reset
colors and init colors didn't help) - there is something wrong between your
terminal and ncurses. Theoretically the terminal should be returned to
initial state after the correct ncurses library ending, but I know about
some problems on BSD and maybe  macOS has some issues too. Only one known
workaround is sending a reset sequence.

**Comment by dark-panda** [comment]
@okbob that `--on-exit-reset` option works just fine so I'll be using that moving forward, thanks.

**Comment by okbob** [comment]
@dark-panda I implemented new option `--on-exit-sgr0`. Can you check it (without `--on-exit-reset`). It is in master branch.
