### ISSUE TITLE
Segfault on empty input

### ISSUE THREAD

**Issue by ethack** [okbob/pspg#213]
I'm getting a segfault when using `--highlight-odd-rec` in combination with `--csv` and empty input. Neither flags by themselves segfault.  It's only the combination of the two with empty input.

```bash
$ pspg --version
pspg-5.5.12

$ echo | pspg --csv --highlight-odd-rec
pspg crashed by signal 11
zsh: done                              echo | 
zsh: segmentation fault (core dumped)  pspg --csv --highlight-odd-rec
```

None of these segfault:
```bash
$ echo | pspg --csv  

$ echo | pspg --highlight-odd-rec

$ echo 1 | pspg --csv --highlight-odd-rec
```

**Comment by okbob** [comment]
should be fixed in 5.5.13

**Comment by ethack** [comment]
Confirmed on my side. Thanks a lot!

**Comment by okbob** [comment]
po 28. 11. 2022 v 18:40 odesílatel ethack ***@***.***> napsal:

> Confirmed on my side. Thanks a lot!
>

Thank you for bug report :)
