### ISSUE TITLE
tabs in fields have adverse effects on columns boundaries and alignment

### ISSUE THREAD

**Issue by slackwhere** [okbob/pspg#214]
The following CSV data with embedded tabs should be enough to see the visual effect. I'm not sure of the best way to represent tabs in the output and maintain proper alignment.  Perhaps provide options to convert them to some number of spaces or strip them? Stripping them would a helpful at the beginning/ending of fields but not the middle.

```
col1,col2,col3
dat1,dat2,dat3
dat1,dat2,dat3
dat1	,dat2,dat3
dat1	,dat2,dat3
dat1	,dat2,dat3
dat1	,dat2	,dat3
dat1	,dat2,dat3
dat1	,dat2	,dat3
dat1	,dat2,dat3
dat1	,dat2,dat3
dat1	,dat2,dat3
dat1	,dat2,dat3
dat1,	dat2,dat3
dat1,	dat2,dat3
dat1,dat2,dat3
dat1,da	t2,dat3
dat1,dat2,dat3
dat1,dat2,dat3
```

**Comment by okbob** [comment]
should be fixed by commit bef5a268fc05898cdb6fee03380b0a2be3a2a822

please, check

**Comment by slackwhere** [comment]
I see that it works for your test4.csv file. But for some reason it's still
not aligning on my test file.

**Comment by okbob** [comment]
should be fixed now

**Comment by slackwhere** [comment]
Yes, that works 👍

Perhaps in the future you would consider a feature request for a setting to
trim whitespace from the beginning/ending of fields? At least in the data
sets that I've been provided it's usually an error that they exist.

Thank you for the quick turnaround.

Wayne

**Comment by okbob** [comment]
I am not sure what is correct design - I just reimplemented behaviour implemented in Postgres. I believe so CSV import in Postgres is very correct, and it doesn't throw tabs. The trimming is easy, when you don't support multilines, but pspg does it - and trimming multiline value requires little bit more complex algorithm (for robust implementation).

**Comment by okbob** [comment]
last commit should to remove outer tabs too. Please, check

**Comment by slackwhere** [comment]
Yes, that works except when the field is quoted and contains a
leading/trailing tab.

"<tab>data",data,data
data,"data<tab>",data

Perhaps that was intentional though?

**Comment by okbob** [comment]
I don't think so any can be cleaned inside quotes
