### ISSUE TITLE
Feature req: freeze-columns as a config file setting

### ISSUE THREAD

**Issue by urandom** [okbob/pspg#217]
Hi,

It looks like freeze-columns is not currently support as input from the config file (https://github.com/okbob/pspg/blob/master/src/config.c#L362). I'd like for it to be there, as I'm always turning of the default "1" when I use pspg

**Comment by okbob** [comment]
Hi

I afraid so saving current freezed columns to config file can be little bit messy (more because freezing is in command menu, not in option menu). 

But you can use `-c` option in command line, and you can set like:

```
export PSQL_PAGER='pspg'
export PSPG_CONF='-c 1'
```

**Comment by urandom** [comment]
Hi okbob

It looks like setting PSPG_CONF='-c 0' doesn't really work, as the first column is still frozen. It also starts ignoring the ~/.pspgconf file as well, which has some other configuration that I like

**Comment by okbob** [comment]
I was wrong - `PSPG_CONF` is path to pspg config file. You should to change the `PSPG` variable. I am sorry.
