### ISSUE TITLE
Shift+MouseWheel -> Horizontal Scrolling

### ISSUE THREAD

**Issue by jk3us** [okbob/pspg#22]
It would be nice to be able to horizontally scroll with your mouse.  Chrome uses Shift+MouseWheel to do this, so I'd suggest that to be used.

**Comment by okbob** [comment]
I am not sure if it is possible with ncurses mouse driver. I'll test it.

**Comment by jk3us** [comment]
I just realized that shift-wheel is caught by my terminal.  I had a vim thing configured that used ctrl (which is why I posted that as the original title):

    nmap <silent> <C-ScrollWheelDown> zL
    nmap <silent> <C-ScrollWheelUp> zH

But some way to easily scroll horizontal would be nice, if possible.

**Comment by okbob** [comment]
Shift MouseWheel doesn't work on some terminals - I hope so Alt MouseWheel is ok too.
