### ISSUE TITLE
segfault when watching non existing --querystream file

### ISSUE THREAD

**Issue by ahirner** [okbob/pspg#222]
Repro:
```
$ pspg --querystream -f doesnotexist -w 2
cannot to open file "doesnotexist" (No such file or directory)
pspg crashed by signal 11
Segmentation fault: 11
```

**Comment by okbob** [comment]
should be fixed by c4f743444fe09db61979feb860330c4f90d6d7ec commit, please check

**Comment by ahirner** [comment]
Thanks! It doesn't crash on a non existing file. Watching an existing file at fixed time intervals also works now. This is great!

One edge case: when the file doesn't exist at first, but is created after the error displays, the file's contents aren't picked up.

I got a crude patch that makes this work, and also if you only want to watch for changes with kqueue/inotify (`--querystream -f query.sql`): https://github.com/ahirner/nix-trickle/blob/main/patches/pspg.patch

So far it works for me, but I'm not sure if the fix is correct and elegant. I can file another issue, if you like.

**Comment by ahirner** [comment]
That fixed it
