### ISSUE TITLE
difference in pgcli and psql table behavior in pspg

### ISSUE THREAD

**Issue by amanvm** [okbob/pspg#226]
Not sure if this is a pgcli issue or pspg, but the table output from pgcli seems off in pspg... The table and data are same as in https://github.com/okbob/pspg/issues/224#issue-1776226772, run this query after loading the table in pgcli and psql:

```
select distinct state_name from us_counties_pop_est_2019;
```

psql output (correct):
<img width="622" alt="Screenshot 2023-06-29 at 3 47 36 PM" src="https://github.com/okbob/pspg/assets/25681815/545d5ce2-5c77-4c64-9b3d-a4b3974e8360">

pgcli output (not correct, see that ``SELECT 51``):
<img width="622" alt="Screenshot 2023-06-29 at 3 48 02 PM" src="https://github.com/okbob/pspg/assets/25681815/c21d3c9c-2b20-4613-8459-a3d09b59e94d">

Same problem is seen with other commands too...
```
\d us_counties_pop_est_2019;
```
psql output (correct):
<img width="714" alt="Screenshot 2023-06-29 at 4 17 01 PM" src="https://github.com/okbob/pspg/assets/25681815/79301c35-4a58-4f1c-b54f-3dc9e2417cb2">

pgcli output (not correct, see the ``Indexes`` section picked in the table):
<img width="622" alt="Screenshot 2023-06-29 at 4 16 44 PM" src="https://github.com/okbob/pspg/assets/25681815/cad12aeb-d540-488d-a573-eadb27477532">

**Comment by okbob** [comment]
pá 30. 6. 2023 v 1:19 odesílatel amanvm ***@***.***> napsal:

> Not sure if this is a pgcli issue or pspg, but the table output from pgcli
> seems off in pspg... The table and data are same as in #224 (comment)
> <https://github.com/okbob/pspg/issues/224#issue-1776226772>, run this
> query after loading the table in pgcli and psql:
>
> select distinct state_name from us_counties_pop_est_2019;
>
> psql output (correct):
> [image: Screenshot 2023-06-29 at 3 47 36 PM]
> <https://user-images.githubusercontent.com/25681815/249917879-545d5ce2-5c77-4c64-9b3d-a4b3974e8360.png>
>
> pgcli output (not correct, see that SELECT 51):
> [image: Screenshot 2023-06-29 at 3 48 02 PM]
> <https://user-images.githubusercontent.com/25681815/249917848-c21d3c9c-2b20-4613-8459-a3d09b59e94d.png>
>
> Same problem is seen with other commands too...
>
> \d us_counties_pop_est_2019;
>
> psql output (correct):
> [image: Screenshot 2023-06-29 at 4 17 01 PM]
> <https://user-images.githubusercontent.com/25681815/249924931-79301c35-4a58-4f1c-b54f-3dc9e2417cb2.png>
>
> pgcli output (not correct, see the Indexes section picked in the table):
> [image: Screenshot 2023-06-29 at 4 16 44 PM]
> <https://user-images.githubusercontent.com/25681815/249924904-cad12aeb-d540-488d-a573-eadb27477532.png>
>
> —
>

It is an issue on pgcli, I think. Probably you use CSV output.
Unfortunately, pgcli adds info about the number of lines in to output. You
can try option --pgcli-fix

**Comment by okbob** [comment]
pá 30. 6. 2023 v 5:36 odesílatel Pavel Stehule ***@***.***>
napsal:

>
>
> pá 30. 6. 2023 v 1:19 odesílatel amanvm ***@***.***> napsal:
>
>>
>>
> It is an issue on pgcli, I think. Probably you use CSV output.
> Unfortunately, pgcli adds info about the number of lines in to output. You
> can try option --pgcli-fix
>

or you can use some other classic format in pgcli. Originally, csv format
was preferred in pgcli, because other formats were terribly slow. But this
issue should be fixed already.

**Comment by okbob** [comment]
I tested pgcli, and it is pgcli issue. It produces "partially" broken CSV, because prints info as part of CSV output. You should to use `--ignore-short-rows` option (of `pspg`) to fix it.

**Comment by amanvm** [comment]
@okbob Thanks, adding that option to pgcli's config for pspg pager resolves the problem.
