### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by karlhorky** [okbob/pspg#235]
I looked through the readme but could not figure out whether this is supported on Windows, via either:

1. Usage via Git Bash, which uses MINGW/MSYS2
2. Usage via WSL2

Ideally it would be great to get an installer via [Chocolatey](https://community.chocolatey.org/packages?q=pspg), to make this as easy as Homebrew installation on macOS/Linux.

**Comment by okbob** [comment]
Any volunteer for this? I don't use windows, so I know minimum about it. pspg is compilable against pdcurses, but I afraid so there is not correct implementation of `newterm` function. I expect so compilation inside WSL2 and Ubuntu should not be a problem.

**Comment by karlhorky** [comment]
## Workaround with `less --header <number>`

Less (installed with Git Bash) supports [a `--header` option](https://man7.org/linux/man-pages/man1/less.1.html#:~:text=that%20new%20file.-,%2D%2Dheader%3DN%5B%2CM%5D,-Sets%20the%20number) which [scrolls header rows along with the page](https://stackoverflow.com/a/71308346/1268612).

This, combined with [the `--chop-long-lines` option](https://man7.org/linux/man-pages/man1/less.1.html#:~:text=%2DS%20or%20%2D%2Dchop%2Dlong%2Dlines) has at least some features of `pspg` without support:

`~/.bash_profile`

```ini
export PSQL_PAGER="less --chop-long-lines --header 1"
```

**Comment by okbob** [comment]
Good to know it - I'll add it to readme

**Comment by okbob** [comment]
54049ec4aad667d850d0754ccbacb500c9a2a576

**Comment by okbob** [comment]
I tested pspg under wsl2 and wrote setup cb2d8ad14d9925eec3a461fab8da56c528e95dad It is just work
