### ISSUE TITLE
Getting issues while trying to query out data with postgis

### ISSUE THREAD

**Issue by anbumech** [okbob/pspg#236]
Query:

postgres=# SELECT streets.gid, streets.name,
  ST_Transform(streets.geom, 4326),
  streets.geom <-> 'SRID=26918;POINT(583571.9 4506714.3)'::geometry AS dist
FROM
  nyc_streets streets
ORDER BY
  dist
LIMIT 3;
sh: pspg: command not found

Expected result (Below output along with column st_transform which is of geometry type):

  gid  |   name    |        dist
-------+-----------+--------------------
 17385 | Wall St   |  0.749987508809928
 17390 | Broad St  | 0.8836306235191059
 17436 | Nassau St | 1.3368280241070414

But the error:
sh: pspg: command not found

Running this in psql (14.10 (Homebrew))

**Comment by okbob** [comment]
I maybe don't understand to your problem. It looks so you don't have installed pspg.
