### ISSUE TITLE
Feature request: better handling of zero row results

### ISSUE THREAD

**Issue by merlinm** [okbob/pspg#24]
**unpaged result**
postgres=# select pid, usename from pg_stat_activity limit 0;
 pid │ usename 
─────┼─────────
(0 rows)

Time: 1.419 ms
postgres=# select pid, usename from pg_stat_activity limit 1;
  pid  │ usename 
───────┼─────────
 22436 │ rms
(1 row)

**paged result**
postgres=# select pid, usename from pg_stat_activity limit 0;
─────┼─────────
─────┼─────────
(0 rows)
Time: 1.002 ms
postgres=# select pid, usename from pg_stat_activity limit 1;
  pid  │ usename 
───────┼─────────
 22436 │ rms
(1 row)

The zero row paged result does not show column names, just the UTF8 border characters.  The column names are present in the textual results, and presumably ought to be shown.

**Comment by okbob** [comment]
Should be fixed, thank you for report
