### ISSUE TITLE
nushell support ❤️ 

### ISSUE THREAD

**Issue by fdncred** [okbob/pspg#240]
As a nushell maintainer, I just wanted to stop by and say, Thanks for supporting nushell. pspg is a really cool tool. It's super fun playing around with it.

For anyone looking to use `pspg` with nushell. These are the settings I've found to help it work the best. We've reorganized/renamed some things.

```nushell
$env.config.footer_mode = never
$env.config.table.header_on_separator = false
$env.config.ls.clickable_links = false
$env.config.table.mode = rounded 
```

**Comment by okbob** [comment]
ne 17. 3. 2024 v 13:52 odesílatel Darren Schroeder ***@***.***>
napsal:

> As a nushell maintainer, I just wanted to stop by and say, Thanks for
> supporting nushell. pspg is a really cool tool. It's super fun playing
> around with it.
>

Thank you :-)


> For anyone looking to use pspg with nushell. These are the settings I've
> found to help it work the best. We've reorganized/renamed some things.
>
> $env.config.footer_mode = never$env.config.table.header_on_separator = false$env.config.ls.clickable_links = false$env.config.table.mode = rounded
>
>
https://github.com/okbob/pspg/commit/9344f497783fc310553b0e1bc11282c0bd9d1a18

**Comment by fdncred** [comment]
looks good. thanks for adding my tips to the readme.

**Comment by okbob** [comment]
ne 17. 3. 2024 v 19:52 odesílatel Darren Schroeder ***@***.***>
napsal:

> looks good. thanks for adding my tips to the readme.
>
Thank you for sending tips

Pavel
