### ISSUE TITLE
Copy functionality trims leading whitespace

### ISSUE THREAD

**Issue by dmfay** [okbob/pspg#244]
I noticed this just now trying to copy a long query plan out (with "Copy All", on Linux and osx both) -- all the indentation is gone:

```
QUERY PLAN
Index Scan using thing_id_pkey on thing __local_0__  (cost=119.95..3500170.93 rows=1 width=320)
Index Cond: (id = 'fa0ed97d-0858-57c8-80f9-31434f76c9bd'::uuid)
Filter: (hashed SubPlan 25)
SubPlan 23
->  Index Scan using stuff_id_pkey on stuff stuff_2  (cost=2927.05..3500042.94 rows=1 width=32)
Index Cond: (id = __local_0__.stuff_id)
"Filter: ((hashed SubPlan 22) AND ....
```

I looked through export.c briefly but didn't see any obvious culprit.

**Comment by okbob** [comment]
čt 27. 6. 2024 v 20:54 odesílatel Dian Fay ***@***.***>
napsal:

> I noticed this just now trying to copy a long query plan out (with "Copy
> All", on Linux and osx both) -- all the indentation is gone:
>
> QUERY PLAN
> Index Scan using thing_id_pkey on thing __local_0__  (cost=119.95..3500170.93 rows=1 width=320)
> Index Cond: (id = 'fa0ed97d-0858-57c8-80f9-31434f76c9bd'::uuid)
> Filter: (hashed SubPlan 25)
> SubPlan 23
> ->  Index Scan using stuff_id_pkey on stuff stuff_2  (cost=2927.05..3500042.94 rows=1 width=32)
> Index Cond: (id = __local_0__.stuff_id)
> "Filter: ((hashed SubPlan 22) AND ....
>
> I looked through export.c briefly but didn't see any obvious culprit.
>
maybe you use default csv format - it does trimming

try to use formatted text format instead, please

**Comment by dmfay** [comment]
that worked, thank you!

**Comment by okbob** [comment]
čt 27. 6. 2024 v 21:00 odesílatel Dian Fay ***@***.***>
napsal:

> that worked, thank you!
>
:-)
