### ISSUE TITLE
Suggested PSQL_PAGER value prevents the theme declared in the `.pspg_conf` file from being applied as expected

### ISSUE THREAD

**Issue by vanderhoop** [okbob/pspg#246]
**Expected behavior:** when pointing pspg to a specific `PSPG_CONF` file, the theme declared in the conf file should be leveraged when opening a pspg session.

**Actual behavior:** when pointing pspg to a specific `PSPG_CONF` file, the theme declared in the file isn't applied correctly due to the `-b` (black and white) flag passed in the suggested `PSQL_PAGER` env var in the README. In my case, I was trying to use the Solarized Dark theme (17), and it wasn't taking.

**Env:**

Mac OS X 10.14.6 using bash

**Possible Solutions**

1. Dropping the `-b` (black and white) flag from the suggested `PSQL_PAGER` env var. This worked for my use case, but I suspect it was put in the suggested env var for a reason. 
2. Adding a callout to the readme about custom theming and the possible effect that the `-b` flag has.

Thoughts?

**Comment by okbob** [comment]
Unfortunately, not only theme related options can be in collision. `pspg` uses priorities of options that is usual in Linux world - the less priority has configuration file, middle priority has environment variables, and top priority has command line options. This is usual, and I don't want to change it. I can add a paragraph to doc about this behaviour. I quietly expected so this behaviour is known and expected. I can imagine, so this concept can be messy, but I don't think so this behaviour is unusual. Do you have some tip, how this paragraph should to look?

**Comment by okbob** [comment]
050d950a17b66b0c242b56b3786e370f36fb517d
