### ISSUE TITLE
Add more key commands like less: ^E ^Y ^D ^U

### ISSUE THREAD

**Issue by jdanbrown** [okbob/pspg#25]
More key commands that many `less` users will naturally reach for:
- ^E scroll window down one line, keeping cursor in place
- ^Y scroll window up one line, keeping cursor in place
- ^D forward a half window
- ^U backward a half window

**Comment by okbob** [comment]
please, send pull request.

**Comment by okbob** [comment]
should be fixed by 48264df034e5ff6c75dff722a7fddac0cec56bdc commit

**Comment by jdanbrown** [comment]
Awesome, thanks! One more issue:
- ^Y suspends the process (using osx 10.11.6, iterm2 3.0.15, bash 4.4.12, psql 9.5.4)

The other keys (^E ^D ^U) work great. Lmk if should open a separate issue for this, or what extra system info I can provide.

**Comment by okbob** [comment]
2017-10-01 19:14 GMT+02:00 Dan Brown <notifications@github.com>:

> Awesome, thanks! One more issue:
>
>    - ^Y suspends the process (using osx 10.11.6, iterm2 3.0.15, bash
>    4.4.12, psql 9.5.4)
>
>
It is work on my comp. Please, can me send stack trace?

>
>
> The other keys (^E ^D ^U) work great. Lmk if should open a separate issue
> for this, or what extra system info I can provide.
>

We can continue in this issue

**Comment by okbob** [comment]
^Y has pretty simple implementation - there is nothing be wrong. Isn't issue on your terminal - some predefined shortcut or some similar?
