### ISSUE TITLE
/, Enter to repeat search

### ISSUE THREAD

**Issue by slotrans** [okbob/pspg#26]
In less, if you press / and type a string to search for, you can later press / and then Enter and it will search for the same string again. Pspg should behave this way as well.

**Comment by mclei-asw** [comment]
Sorry, but this does not work. I have to use non-standard 'n' and 'N' for search the same string again. Using just '/' does not work.

**Comment by okbob** [comment]
I implemented empty search differently - it clean the searching. I tested n, and N in less and it is work same.

**Comment by mclei-asw** [comment]
Ok, you are right with n and N in less. But empty '/' is used more often I think. Please, please :-)

**Comment by okbob** [comment]
pá 15. 3. 2019 v 16:54 odesílatel mclei-asw <notifications@github.com>
napsal:

> Ok, you are right with n and N in less. But empty '/' is used more often I
> think. Please, please :-)
>
I am sorry. I don't plan to do it. With my implementation (although it can
be different than less) I don't need special command for cleaning searching
result.
