### ISSUE TITLE
Segfault when showing function definition

### ISSUE THREAD

**Issue by clad** [okbob/pspg#37]
\sf functionname results in a segmentation fault

**Comment by okbob** [comment]
It is working on my comp. Please, can send more info, configuration, example of function or backtrace?

**Comment by clad** [comment]
Only some functions cause it, here's a test one that does-

[pspg.function.test.txt](https://github.com/okbob/pspg/files/1507531/pspg.function.test.txt)

[pspg.trace.txt](https://github.com/okbob/pspg/files/1507582/pspg.trace.txt)

**Comment by okbob** [comment]
I am able to reproduce it.

**Comment by okbob** [comment]
should be fixed by f58897513000589e1fa94a695aedd10d19838a6a commit. Please, test it.

**Comment by clad** [comment]
Yes, that fixed my issue. Thanks!

**Comment by okbob** [comment]
perfect
