### ISSUE TITLE
supporting non-color terminals

### ISSUE THREAD

**Issue by cdr8H** [okbob/pspg#38]
To support non-color terminals, I would suggest to evaluate the 'b' command line switch (black-withe style):

Line 2414: if(!has_colors()) -> if(!has_colors() && style != 0)

**Comment by okbob** [comment]
42f6ae0c0a6370e3766433ac59ea95b1bd211eb3 

I have not any possibility to test it.

**Comment by okbob** [comment]
After some thinking I am not sure if this change is correct. The 0 style .. black/white uses colours (only two, but uses it). So real non color terminal should not be used. In this case, the colours should not be used only other video attributes, and this style is not supported yet. Probably without significant refactoring should not be supported ever.
