### ISSUE TITLE
Highlighting search results

### ISSUE THREAD

**Issue by ChristophBerg** [okbob/pspg#46]
Hi,
it would be nice if pspg would highlight search results, both in the current line where the cursor is, but also in other lines, so it's immediately obvious if there are more hits on screen (with possibly more hits to the left or right, but assuming the hits are in one column only, that won't be a problem in practise). less does this by default, see -g and -G, but I'm not sure it needs to be configurable.
Thanks!

**Comment by okbob** [comment]
It is in ToDo. But probably not in few months - I have to work on other project.

**Comment by okbob** [comment]
hi, please check last commit. This is initial implementation.

**Comment by ChristophBerg** [comment]
Thanks!
It looks mostly ok, there's a minor issue with left/right scrolling when there's multiple hits per line - I was searching for '0' in the provided pg_class.txt file, and it didn't always put the current hit into the visible area when jumping around with n/N.
(Please also consider hilighting all the hits in the currently visible area, that is the reason I was asking for this feature. I guess it's on the TODO list anyway, just reiterating here.)
Cheers!

PS: The new bookmark feature is pretty cool. Would you consider keeping Alt+j/k as down/up, and choose something else for setting the bookmark, maybe Alt+b? Alt+j/i is confusing for vi users.

**Comment by okbob** [comment]
I have a plan to highlight all, via ALT/  or ALT ? command, 

I design this interface after mcedit - but I can design some Vi bookmarks interface and use different keys then.

**Comment by okbob** [comment]
please, recheck last commit - searching 0 should to work

**Comment by okbob** [comment]
I used google little bit and I din't find a reason why ALT i,j should be confusing for vi users?

**Comment by ChristophBerg** [comment]
> I have a plan to highlight all, via ALT/  or ALT ? command, 

Imho it should do that by default, maybe with an --highlight-all
option. (less does that by default, and has --hilite-search to disable
it.) I realize this is deep into personal preference land :)

> I design this interface after mcedit - but I can design some Vi bookmarks interface and use different keys then. 
> I used google little bit and I din't find a reason why ALT i,j should be confusing for vi users?

There is already j/k for down/up movement (which I heavily use),
Alt+j/k for down/up to next bookmark would be consistent with that.

> please, recheck last commit - searching 0 should to work

Looks good, thanks!

Christoph

**Comment by okbob** [comment]
please, check last commit

**Comment by ChristophBerg** [comment]
Thanks!
