### ISSUE TITLE
0.9 thinks it's 0.8

### ISSUE THREAD

**Issue by ilovezfs** [okbob/pspg#48]
https://github.com/okbob/pspg/blob/0.9.0/src/pspg.c#L31

**Comment by ilovezfs** [comment]
also https://github.com/okbob/pspg/blob/0.9.0/pspg.spec#L6

**Comment by okbob** [comment]
should be fixed now.

**Comment by ilovezfs** [comment]
perfect https://github.com/Homebrew/homebrew-core/pull/22244
