### ISSUE TITLE
Value width miscalculated

### ISSUE THREAD

**Issue by g0tar** [okbob/pspg#52]
`PAGER="./pspg -s 11 -g -i -F" psql -c "SELECT (CASE WHEN random()<0.5 then 'ó' else '-' END),md5(random()::text) FROM generate_series(1,80)"`

generates following output (note the misalignments):

```
 ó    |973263148f6c1da850c5b82f44bedd
 -    | 98d546af5b4f08861a8e0291b3117c22
 ó    |3e7a73ef2ae53719d7a5eaa88b6f41
 ó    |9a48e5cb0b378cbc9c72721c983adb
 -    | 0d5c73047d42b16a3ab7f09a845f1fe2
 -    | 087f7bc9a684617fc9c5522c0ee79fef
 -    | 81db99d85a7c63dc447b5675a0774bbb
 ó    |f00ab7b5e450eb314d8b9f1e4875db
 -    | 2ca1b394e873b1168c0e4eac829ac7ca
```

This happens with 8-bit (non unicode) locale (ISO8859-2 in my case).

Edit: it's better visible with constant value in 2nd column ("abcdef"):

```
 -    | abcdef
 ó    |cdef
 -    | abcdef
 ó    |cdef
 -    | abcdef
 -    | abcdef
 ó    |cdef
```

**Comment by okbob** [comment]
2018-03-03 17:49 GMT+01:00 g0tar <notifications@github.com>:

> PAGER="./pspg -s 11 -g -i -F" psql -c "SELECT (CASE WHEN random()<0.5 then
> 'ó' else '-' END),md5(random()::text) FROM generate_series(1,80)"
>
> generates following output (note the misalignments):
>
>  ó    |973263148f6c1da850c5b82f44bedd
>  -    | 98d546af5b4f08861a8e0291b3117c22
>  ó    |3e7a73ef2ae53719d7a5eaa88b6f41
>  ó    |9a48e5cb0b378cbc9c72721c983adb
>  -    | 0d5c73047d42b16a3ab7f09a845f1fe2
>  -    | 087f7bc9a684617fc9c5522c0ee79fef
>  -    | 81db99d85a7c63dc447b5675a0774bbb
>  ó    |f00ab7b5e450eb314d8b9f1e4875db
>  -    | 2ca1b394e873b1168c0e4eac829ac7ca
>
>
>
This happens with 8-bit (non unicode) locale (ISO8859-2 in my case).
>
I am able to reproduce it. Thank you for info.

**Comment by okbob** [comment]
please, try master. For 8bit encoding use pspg option --force8bit and shell variable LC_CTYPE should be correct - export LC_CTYPE=cs_CZ.latin2

**Comment by okbob** [comment]
I removed option --force8bit. This should be decided automatic

**Comment by g0tar** [comment]
Thanks, seems to work properly now.

BTW - search backwards doesn't work. Pressing 'N' segfaults immediately, while '?' and pattern waits a few seconds before crashing. Do you reproduce it, or it's worth creating new ticket?

**Comment by okbob** [comment]
should be fixed now. Please, check it.

**Comment by g0tar** [comment]
Thank you again!

Now, there is a glitch in N-search after ?-search. Looking for "previous" match after "reversed" search in fact search forwards, however there is some weird cycling:

PAGER="/dev/shm/pspg/pspg -s 11 -g -i -F" psql -c "select * from generate_series(1,100000)"
?5258 => Not found (we're at the beginning of the results)
N => 5258 (I need to manually rewind a page, but not always)
N => 15258
...
N => 95258
N => Not found (we're at the end of the results)
N => 95258
N => Not found, and now, as long as "Not found" message is being displayed:
N => 85248 (note this is NOT *258 but 248)
N => 85258

Apparently some cleanup is postponed until "Not found" message disappears and is not performed if user manages to invoke new command, as a similar glitch can be made with search to be stucked in a single result.

**Comment by okbob** [comment]
The design of searching and messages cleaning is relative simple. So there can be some corner cases. Probably there must be better internal description of current searching command

**Comment by okbob** [comment]
last commit should to fix unwanted search direction. Still there are small corner case on the end. When not found is raised, then search cursor is reseted - new searching in well direction starting from begin of cursor row, so on the end of data is possible cycle - not found, found on current row, not found, ...

**Comment by okbob** [comment]
please, can you check last fix. I would to raise bugfix release?

**Comment by g0tar** [comment]
As for finding the matches it seems to work correctly now. Also I didn't manage to SEGV, as it happened previously.

There is however still an issue with highlighting wrong line (not the one, that matches), apparently related to distance between the matches:

`psql -c "SELECT *,g FROM (SELECT g, null AS value FROM generate_series(1,2811) g UNION ALL VALUES (932,('xxhapa')),(2423,('hapaXX'))) t ORDER BY 1"`

/hapa
n
N

- note the line which becomes highlighted (2 above the actual match) and the reversed background in the place. where match is found 2 lines below.

**Comment by okbob** [comment]
I am able to reproduce it.

**Comment by okbob** [comment]
Last commit should to fix it. Please, check it.

**Comment by g0tar** [comment]
Seems to work fine. The last thing I've noticed is top status-line disappearing with "Not found" message.

**Comment by g0tar** [comment]
And some minor twek for help message: both options take argument ranging from 0, not 1:

```
  -s N           set color style number (1..14)
  -c N           fix N columns (1..4)
```

**Comment by okbob** [comment]
2018-03-11 11:12 GMT+01:00 g0tar <notifications@github.com>:

> Seems to work fine. The last thing I've noticed is top status-line
> disappearing with "Not found" message.
>
should be fixed now too.

**Comment by okbob** [comment]
please, can you do check?

**Comment by okbob** [comment]
no reply
