### ISSUE TITLE
Column management

### ISSUE THREAD

**Issue by g0tar** [okbob/pspg#54]
Just an idea of feature request: since pspg is aware of columns in psql output, it could as well allow to:
1. hide columns from the view - especially usefull for SELECT * queries for wide tables, since there is no "SELECT all_except_specified_columns",
2. reorder columns - also saves typing of all the column names instead of "*", since PostgreSQL itself doesn't allow to change default order and on-disk structure might be subject of on-purpose alignment,
3. ellipse specified columns,
4. show expanded (psql -x) version of the record when selected and (e.g.) ENTER pressed.
5. provide maximum column width as a command line argument.

User interface:
c - enter column management mode, cursor goes to top-line header, hidden columns are displayed dimmed
left/right arrows - selecting column
h - toggle "hide"
</> - shrink/expand column
m - mark column for "move" operation, left/right arrows to position, enter to accept
c/enter - exit column management mode

**Comment by okbob** [comment]
2018-03-04 19:37 GMT+01:00 g0tar <notifications@github.com>:

> Just an idea of feature request: since pspg is aware of columns in psql
> output, it could as well allow to:
>
>    1. hide columns from the view - especially usefull for SELECT *
>    queries for wide tables, since there is no "SELECT
>    all_except_specified_columns",
>    2. reorder columns - also saves typing of all the column names instead
>    of "*", since PostgreSQL itself doesn't allow to change default order and
>    on-disk structure might be subject of on-purpose alignment,
>    3. ellipse specified columns,
>    4. show expanded (psql -x) version of the record when selected and
>    (e.g.) ENTER pressed.
>    5. provide maximum column width as a command line argument.
>
> User interface:
> c - enter column management mode, cursor goes to top-line header, hidden
> columns are displayed dimmed
> left/right arrows - selecting column
> h - toggle "hide"
> </> - shrink/expand column
> m - mark column for "move" operation, left/right arrows to position, enter
> to accept
> c/enter - exit column management mode
>
All your proposed changes needs rewriting pspg. Currently pspg store
original result in memory and provides some independent views on these
data. My code doesn't expect dynamic width of these data. It is just pager.

Your proposed features requires different technique - tabular data should
be parsed and stored inside some smarter structure than just list of lines
- maybe some column store. Then these data can be displayed very dynamic.
But it is not possible on this version of pspg.

Is another question to use as pager some Unix TUI spreadsheets like sc-im?

This version of pspg was designed as prototype - it is my first ncurses
application - and test, if is possible to have a multiple scrolling areas.
Unfortunately my free time for this app is now near to zero, so I don't
expect significant changes this or next year.  But I am satisfied so I
showed so is possible to write special pager for tabular data and this
concept can be enhanced. But not probably not by my - I hadn't plan to
spend another summer on this topic :)

**Comment by okbob** [comment]
I wrote your ideas to Possible ToDo section in Readme.md

**Comment by okbob** [comment]
Noticed in ToDo
