### ISSUE TITLE
Building on macOS

### ISSUE THREAD

**Issue by schinckel** [okbob/pspg#6]
I was able to build on macOS Sierra by linking against ncurses, instead of ncursesw.

I don't know how to make this a conditional in the Makefile.

**Comment by palmerj** [comment]
How did you manually build in on MacOSX?

**Comment by schinckel** [comment]
I just edited the Makefile, and changed `-lncursesw` into `-lncurses`

I'm not sure if that was with the system version of `ncurses`, or a `brew install ncurses`.

**Comment by palmerj** [comment]
Thanks complied.  Did you get lots of graphical errors on Mac. I did. Also when displaying the psql help the command test was not visible.

**Comment by schinckel** [comment]
I think I used one of the other themes, and that made the rendering better.

**Comment by okbob** [comment]
I fixed lot of errors, I hope so I fixed a display errors too - probably related to older ncurses version. Please, test it.
