### ISSUE TITLE
history in search

### ISSUE THREAD

**Issue by dk** [okbob/pspg#62]
Hi!

I should very much like to ask to add history in searches, like "less" does: one types '/', then can use keys up and down. Thanks for the great product!

/dk

**Comment by okbob** [comment]
The commit a4d7d1990283dbd77cf44faeaeb91749caa46a11 should to do it

**Comment by dk** [comment]
Thank you, it does it! It has some problems on older systems with readline v5, but I'll sent a pull request shortly. Thanks again!
