### ISSUE TITLE
Hang on \dx+ output with less-status-bar

### ISSUE THREAD

**Issue by df7cb** [okbob/pspg#66]
The attached file (from `\dx+ postgis`) causes pspg to consume 100% CPU: `./pspg --less-status-bar < dx-postgis.txt`. It works without --less-status-bar.
[dx-postgis.txt](https://github.com/okbob/pspg/files/1931128/dx-postgis.txt)

**Comment by okbob** [comment]
should be fixed now.

**Comment by okbob** [comment]
please, can check it?
