### ISSUE TITLE
psql '\s' command to display history causes 'Segmentation fault: 11' on MacOS

### ISSUE THREAD

**Issue by hunsakerbn** [okbob/pspg#67]
When I tried to use '\s' in psql (with PAGER set to pspg) I got no output.  Further investigation indicated that pspg was exiting with a 'Segmentation fault: 11'. 
I tracked this down to pspg.c line 876 (in master):
		desc->headline_size = strlen(desc->headline);
A fix was not obvious to me.

**Comment by okbob** [comment]
2018-06-05 22:33 GMT+02:00 Bruce Hunsaker <notifications@github.com>:

> When I tried to use '\s' in psql (with PAGER set to pspg) I got no output.
> Further investigation indicated that pspg was exiting with a 'Segmentation
> fault: 11'.
> I tracked this down to pspg.c line 876 (in master):
> desc->headline_size = strlen(desc->headline);
> A fix was not obvious to me.
>

please, can me send o output of \s command - or some minimalistic version
that help me to repeate this issue? It is working for me. I can do ugly
fix, but I would to find some untested path

you can check so this file does what is expected: pspg -f yourfile and it
should to crash.


Thank you

Pavel

**Comment by okbob** [comment]
2018-06-05 22:45 GMT+02:00 Pavel Stehule <pavel.stehule@gmail.com>:

>
>
> 2018-06-05 22:33 GMT+02:00 Bruce Hunsaker <notifications@github.com>:
>
>> When I tried to use '\s' in psql (with PAGER set to pspg) I got no
>> output. Further investigation indicated that pspg was exiting with a
>> 'Segmentation fault: 11'.
>> I tracked this down to pspg.c line 876 (in master):
>> desc->headline_size = strlen(desc->headline);
>> A fix was not obvious to me.
>>
>
> please, can me send o output of \s command - or some minimalistic version
> that help me to repeate this issue? It is working for me. I can do ugly
> fix, but I would to find some untested path
>
> you can check so this file does what is expected: pspg -f yourfile and it
> should to crash.
>

 <-->if (desc->border_head_row != -1)
<-->{
<--><-->desc->headline = desc->rows.rows[desc->border_head_row];
<--><-->desc->headline_size = strlen(desc->headline);

It is interesting - looks like saving to memory had to fails somewhere.

**Comment by hunsakerbn** [comment]
I haven't had luck creating a small test case but it looks like the problem has something to do with
SQL comment lines.  A line that starts with '--' (two dashes) somewhere toward the bottom of history seems to cause the problem. But it also seems to depend on how many lines are in the history.
However putting in some debug, It showed that 'border_head_row' was set to 1339, which is an SQL comment line with the contents "-- Workshop leader information".
If I remove that line then the problem goes away.
If I change the text of the comment, the problem persists.
If I put a different character before the "--" (such as "x--") the problem goes away.

Hope that helps.

**Comment by okbob** [comment]
2018-06-06 3:56 GMT+02:00 Bruce Hunsaker <notifications@github.com>:

> I haven't had luck creating a small test case but it looks like the
> problem has something to do with
> SQL comment lines. A line that starts with '--' (two dashes) somewhere
> toward the bottom of history seems to cause the problem. But it also seems
> to depend on how many lines are in the history.
> However putting in some debug, It showed that 'border_head_row' was set to
> 1339, which is an SQL comment line with the contents "-- Workshop leader
> information".
> If I remove that line then the problem goes away.
> If I change the text of the comment, the problem persists.
> If I put a different character before the "--" (such as "x--") the problem
> goes away.
>
please, check last fix

Regards

Pavel

**Comment by hunsakerbn** [comment]
Still broken :(

**Comment by okbob** [comment]
2018-06-06 15:08 GMT+02:00 Bruce Hunsaker <notifications@github.com>:

> Still broken :(
>
it is strange. What is value of border_head_row?

**Comment by hunsakerbn** [comment]
border_head_row is 1339.  The following patch seems to fix it, but it's probably the wrong way to do it.
+++ pspg.c      2018-06-06 07:44:16.548963411 -0600
@@ -878,6 +878,9 @@

        desc->headline_char_size = 0;

+       if (desc->border_head_row >= 10)
+               desc->border_head_row = -1;
+
        if (desc->border_head_row != -1)
        {
                desc->headline = desc->rows.rows[desc->border_head_row];

**Comment by okbob** [comment]
2018-06-06 15:48 GMT+02:00 Bruce Hunsaker <notifications@github.com>:

> border_head_row is 1339. The following patch seems to fix it, but it's
> probably the wrong way to do it.
>

I don't understand how it is possible, after patching - my patch was
similar to your

https://github.com/okbob/pspg/commit/3795670a753f2241d7e8e33a4160da0d169375ac

/*
* border headline cannot be higher than 1000, to simply find it
* in first row block. Higher number is surelly wrong, probably
* some comment.
*/
if (desc->border_top_row >= 1000)
desc->border_top_row = -1;

if (desc->last_row != -1)
desc->maxy = desc->last_row;

desc->headline_char_size = 0;

if (desc->border_head_row != -1)
{
    desc->headline = desc->rows.rows[desc->border_head_row];
     desc->headline_size = strlen(desc->headline);

So border_head_row on this problematic place cannot be 1339

Maybe patch was not applyed well?

**Comment by hunsakerbn** [comment]
On 06 Jun 18 11 50, Pavel Stehule wrote:
> 2018-06-06 15:48 GMT+02:00 Bruce Hunsaker <notifications@github.com>:
> > border_head_row is 1339. The following patch seems to fix it, but it's
> > probably the wrong way to do it.
> >
> I don't understand how it is possible, after patching - my patch was
> similar to your
> https://github.com/okbob/pspg/commit/3795670a753f2241d7e8e33a4160da0d169375ac

Your patch is a check for sanity on border_top_row, which is different
than mine for border_head_row.  So I put in 2 debug statements, one
before your patch and one before mine, and got this:

  border_top_row: -1
  border_head_row: 1337

So in my history file, border_top_row was not found, but
border_head_row was found at line 1337. (Different from 1339 above
since I played with the file a bit). Below is a snippet
of the code containing both changes and my debug:

  fprintf(stderr,"border_top_row: %d\n",desc->border_top_row);
  if (desc->border_top_row >= 1000)
    desc->border_top_row = -1;

  if (desc->last_row != -1)
    desc->maxy = desc->last_row;

  desc->headline_char_size = 0;

  fprintf(stderr,"border_head_row: %d\n",desc->border_head_row);
  if (desc->border_head_row >= 10)
    desc->border_head_row = -1;

  if (desc->border_head_row != -1)
  {
    desc->headline = desc->rows.rows[desc->border_head_row];
    desc->headline_size = strlen(desc->headline);


The only place I see that sets border_head_row is here (pspg.c:805 ...)

    if (desc->border_head_row == -1 && desc->border_top_row == -1 && isTopLeftChar(line))
    {
      desc->border_top_row = nrows;
      desc->is_expanded_mode = is_expanded_header(opts, line, NULL, NULL);
    }
    else if (desc->border_head_row == -1 && isHeadLeftChar(line))
    {
      desc->border_head_row = nrows;

I read this to mean that border_head_row can be set even when border_top_row is not,
and isHeadLeftChar(line) will match the first SQL comment it finds, which
in my case is on line 1337.

Does that help any?

-- 
Bruce Hunsaker

**Comment by okbob** [comment]
2018-06-06 21:39 GMT+02:00 Bruce Hunsaker <notifications@github.com>:

> On 06 Jun 18 11 50, Pavel Stehule wrote:
> > 2018-06-06 15:48 GMT+02:00 Bruce Hunsaker <notifications@github.com>:
> > > border_head_row is 1339. The following patch seems to fix it, but it's
> > > probably the wrong way to do it.
> > >
> > I don't understand how it is possible, after patching - my patch was
> > similar to your
> > https://github.com/okbob/pspg/commit/3795670a753f2241d7e8e33a4160da
> 0d169375ac
>
> Your patch is a check for sanity on border_top_row, which is different
> than mine for border_head_row. So I put in 2 debug statements, one
> before your patch and one before mine, and got this:
>

I was wrong, I would to check border_head_row, but should be checked both

https://github.com/okbob/pspg/commit/cc7ed31df8dbec012207c216d22871611c6ad285


> border_top_row: -1
> border_head_row: 1337
>
> So in my history file, border_top_row was not found, but
> border_head_row was found at line 1337. (Different from 1339 above
> since I played with the file a bit). Below is a snippet
> of the code containing both changes and my debug:
>

I have two kind of counters, - global [0..x], and row block[0..999]

because I use direct access to row block, border_top_row and
border_head_row have to be limited to 999. Probably there is not a sense to
be higher than 100.

This is a heuristic, that try to recognize tabular result and text result.


>
> fprintf(stderr,"border_top_row: %d\n",desc->border_top_row);
> if (desc->border_top_row >= 1000)
> desc->border_top_row = -1;
>
> if (desc->last_row != -1)
> desc->maxy = desc->last_row;
>
> desc->headline_char_size = 0;
>
> fprintf(stderr,"border_head_row: %d\n",desc->border_head_row);
> if (desc->border_head_row >= 10)
> desc->border_head_row = -1;
>
> if (desc->border_head_row != -1)
> {
> desc->headline = desc->rows.rows[desc->border_head_row];
> desc->headline_size = strlen(desc->headline);
>
>
> The only place I see that sets border_head_row is here (pspg.c:805 ...)
>
> if (desc->border_head_row == -1 && desc->border_top_row == -1 &&
> isTopLeftChar(line))
> {
> desc->border_top_row = nrows;
> desc->is_expanded_mode = is_expanded_header(opts, line, NULL, NULL);
> }
> else if (desc->border_head_row == -1 && isHeadLeftChar(line))
> {
> desc->border_head_row = nrows;
>
> I read this to mean that border_head_row can be set even when
> border_top_row is not,
> and isHeadLeftChar(line) will match the first SQL comment it finds, which
> in my case is on line 1337.
>
> Does that help any?


it helps me. I did a error.

Please, check it now.

**Comment by hunsakerbn** [comment]
That fixes it.  Thank you.
