### ISSUE TITLE
Unicode issue?

### ISSUE THREAD

**Issue by loveencounterflow** [okbob/pspg#69]
I cloned and compiled `pspg` to get to grips with some faulty display issues I've experienced lately.

When I do 

```sh
PAGER='~/io/pspg/pspg' psql -U mojikura -c "\
  select to_hex( cid ), chr( cid ) from \
  generate_series( x'2cea0'::integer, x'2cec0'::integer ) as x ( cid );"
```

I get the expected result when display is done without a pager (by zooming out):

```
╔════════╤═════╗
║ to_hex │ chr ║
╠════════╪═════╣
║ 2cea0  │ 𬺠  ║
║ 2cea1  │ 𬺡  ║
║ 2cea2  │ 𬺢  ║
║ 2cea3  │ 𬺣  ║
...
║ 2ceaf  │ 𬺯  ║
║ 2ceb0  │ 𬺰  ║
║ 2ceb1  │ 𬺱  ║
║ 2ceb2  │ 𬺲  ║
║ 2ceb3  │ 𬺳  ║
...
║ 2cec0  │ 𬻀  ║
╚════════╧═════╝
```

I can copy & paste that into a text editor for inspection, and even the replacement characters for the undefined codepoints have the correct encodings (i.e. the codepoints are correctly preserved even though their display uses a replacement figure).

But when I enlarge the font to make `pspg` kick in, I get this:

```
╔════════╤═════╗
║ to_hex │ chr ║
╠════════╪═════╣
║ 2cea0  │ 𬺠  ║
║ 2cea1  │ 𬺡  ║
║ 2cea2  │    ║
║ 2cea3  │    ║
...
║ 2ceaf  │    ║
║ 2ceb0  │    ║
║ 2ceb1  │    ║
║ 2ceb2  │    ║
║ 2ceb3  │    ║
...
║ 2cec0  │    ║
╚════════╧═════╝
```

In this case, all codepoints starting from `0x2cea2` are turned into spaces (`0x20`), visually and physically. This happens consistently using bash, zsh, and several terminal emulators, so the cause must lie with `pspg`. My suspicion is that this is a Unicode versioning bug, as [7473 CJK characters were added in the relevant section of Unicode](https://www.unicode.org/versions/Unicode10.0.0/) in version 10. 

On a somehwat related note, zsh—but not bash, it would seem—replaces codepoints that it doesn't feel at ease with by numerical references, so pasting `2ceb0 𬺰` into the zsh terminal displays `2ceb0 <0002ceb0>`, which is super annoying. My guess is that zsh wants to be smart and helpful and avoid non-printable characters in the console, but the libraries that it relies on are not recent enough to cover Unicode version 10.

**Comment by okbob** [comment]
Is possible so tables used in pspg is not fresh. Probably inside ucs_wcwidth function.  Please, can you look there?

**Comment by okbob** [comment]
looks like multiple bugs - probably. My routine is not fully correct display length 2ceb0 chars and higher, but surprisingly it is not main issue. In my test I have little bit different output then your terminal

<pre>
┌────────┬────────┬─────┐
│  cid   │ to_hex │ chr │
╞════════╪════════╪═════╡
│ 183968 │ 2cea0  │ 𬺠  │
│ 183969 │ 2cea1  │ 𬺡  │
│ 183970 │ 2cea2  │    │
│ 183971 │ 2cea3  │    │
│ 183972 │ 2cea4  │    │
│ 183973 │ 2cea5  │    │
│ 183974 │ 2cea6  │    │
│ 183975 │ 2cea7  │    │
│ 183976 │ 2cea8  │    │
│ 183977 │ 2cea9  │    │
│ 183978 │ 2ceaa  │    │
│ 183979 │ 2ceab  │    │
│ 183980 │ 2ceac  │    │
│ 183981 │ 2cead  │    │
│ 183982 │ 2ceae  │    │
│ 183983 │ 2ceaf  │    │
│ 183984 │ 2ceb0  │ 𬺰  │
│ 183985 │ 2ceb1  │ 𬺱  │
│ 183986 │ 2ceb2  │ 𬺲  │
│ 183987 │ 2ceb3  │ 𬺳  │
│ 183988 │ 2ceb4  │ 𬺴  │
│ 183989 │ 2ceb5  │ 𬺵  │
│ 183990 │ 2ceb6  │ 𬺶  │
│ 183991 │ 2ceb7  │ 𬺷  │
│ 183992 │ 2ceb8  │ 𬺸  │
│ 183993 │ 2ceb9  │ 𬺹  │
│ 183994 │ 2ceba  │ 𬺺  │
│ 183995 │ 2cebb  │ 𬺻  │
│ 183996 │ 2cebc  │ 𬺼  │
│ 183997 │ 2cebd  │ 𬺽  │
│ 183998 │ 2cebe  │ 𬺾  │
│ 183999 │ 2cebf  │ 𬺿  │
│ 184000 │ 2cec0  │ 𬻀  │
└────────┴────────┴─────┘
(33 rows)
</pre>
And I tested behave of ncurses, and looks so ncurses doesn't show some chars correctly. I have most fresh ncurses version and probably I have most correct result. Extensions F starts with U+2CEB0.
pspg doesn't try to place multispace chars preciously - it is work for ncurses. And if ncurses fails, then I cannot do more. Fixing this issue requires significant redesign of pspg. I am sorry. I cannot to fix this issue.

**Comment by loveencounterflow** [comment]
Well, that's good and bad news I guess... at least you're seeing codepoints U+2CEB0 and above rendered as glyphs, not spaces in pspg. My version of ncurses:

```
ncurses5-config --version
6.0.20160213
```

Is that too old?

**Comment by okbob** [comment]
2018-07-09 17:12 GMT+02:00 loveencounterflow <notifications@github.com>:

> Well, that's good and bad news I guess... at least you're seeing
> codepoints U+2CEB0 and above rendered as glyphs, not spaces in pspg. My
> version of ncurses:
>
> ncurses5-config --version
> 6.0.20160213
>
> Is that too old?
>
It is more than 2 years old

I have

[root@nemesis pspg-master]# ncurses6-config --version
6.1.20180224

But I have fresh Fedora 28

**Comment by loveencounterflow** [comment]
OK so that will be the cause then. Thanks for the consideration!
