### ISSUE TITLE
first column can't be wide

### ISSUE THREAD

**Issue by dturon** [okbob/pspg#7]
Hi,

i found problem with wide column (output of public key), can be tested with:
--not working (empty screen)
SELECT repeat('A','1000');
--works
SELECT 'a', repeat('A','1000');
--not working
SELECT repeat('A','1000'), 'a';

but maybe caused by some local environment settings...

David

**Comment by dturon** [comment]
Caused by LOCK first column, after release with key '0' works:)

**Comment by okbob** [comment]
sure - fixed columns don't scroll ever
