### ISSUE TITLE
Latest version 1.3.0 or 1.2.2?

### ISSUE THREAD

**Issue by ilovezfs** [okbob/pspg#73]
https://github.com/okbob/pspg/releases/latest points to 1.2.2 but there is also a 1.3.0 tag.

**Comment by okbob** [comment]
2018-08-04 7:47 GMT+02:00 ilovezfs <notifications@github.com>:

> https://github.com/okbob/pspg/releases/latest points to 1.2.2 but there
> is also a 1.3.0 tag.
>

Latest stable is 1.2.2.

I did strong refactoring in 1.3.0 and I am waiting if somebody reports
errors.

**Comment by ilovezfs** [comment]
Ah OK. Thanks for clearing that up! Note that you can explicitly mark 1.3.0 as a pre-release to remove any ambiguity.
