### ISSUE TITLE
Resizing problems

### ISSUE THREAD

**Issue by lacanoid** [okbob/pspg#75]
pspg sometimes gets the initial terminal size wrong, showing a bit of a mess.
See the screenshots:

![resize1](https://user-images.githubusercontent.com/12818651/45761179-04358780-bc2c-11e8-83fd-e2430231da29.png)

![resize2](https://user-images.githubusercontent.com/12818651/45761184-0697e180-bc2c-11e8-94be-b32cb8b856e9.png)

Note that while pspg is actually running, it resizes ok.
The problem occurs when running another query afterwards, pspg starts up the wrong size, apparently using the original terminal size when psql was started. If psql is quit and restarted, the size is again ok.

How to reproduce:
- run a query
- resize a terminal
- quit pspg
- run a query again
- problem!!!

Checking the terminal, COLUMNS and LINES environment variables are not set.
However, "stty -a" seems to always get the terminal size right.

Specifically, this happens in MacOS terminal, running psql+pspg on remote linux. 
Not sure about other terminal emulators, but I can test if needed.

**Comment by okbob** [comment]
Hi,
I believe so this doesn't work, but I have not MaxOS, and it is working without any problem on Linux. It looks like ncurses issue (maybe psql issue).  I can, and I did enforce reinitilize COLUMNS, LIKE values on start. Please, check last commit. It helps?

**Comment by lacanoid** [comment]
Seems to work fine now! Thanks!

**Comment by lacanoid** [comment]
Might be worth mentioning somewhere that libncursesw needs to be installed for compile...

**Comment by okbob** [comment]
If you have some ideas how to enhance README, please, send me it. I am living in my bubble - linux C coder, and have not too deep ideas, what is necessary for other users.
