### ISSUE TITLE
Ascii borders for menu

### ISSUE THREAD

**Issue by thorstenkampe** [okbob/pspg#78]
The menu borders are not displayed correctly on Windows (ConEmu - see below) - Mintty works fine.  Would it be possible to add an option for ASCII menus similar to default Unicode border for tables?
![image](https://user-images.githubusercontent.com/475462/47257932-a1d2df80-d494-11e8-927d-514bf6d51276.png)

**Comment by okbob** [comment]
It is small miracle so it works on windows ever. Please, try last commit and option `-a`

**Comment by thorstenkampe** [comment]
Not Windows - rather Cygwin (on Windows). It looks wonderful now, thanks for the quick fix:
![image](https://user-images.githubusercontent.com/475462/47258427-507a1e80-d49b-11e8-9260-e0fb3fa4ce2a.png)

**Comment by okbob** [comment]
With pleasure
