### ISSUE TITLE
config to default

### ISSUE THREAD

**Issue by harmnot** [okbob/pspg#83]
how to make the pspg to be default ?  so I don't type `\pset pager always ` anymore evertime I open my database postgres

**Comment by okbob** [comment]
it is about psql configuration. You can create in your home directory file `.psqlrc` and there you cna write `\pset pager always`. 

https://www.digitalocean.com/community/tutorials/how-to-customize-the-postgresql-prompt-with-psqlrc-on-ubuntu-14-04
