### ISSUE TITLE
Feature request: Toggle line breaking

### ISSUE THREAD

**Issue by boerwastaken** [okbob/pspg#84]
Sometimes, as when `\d+`-ing a view, one desires to select and copy-paste something that spans multiple screen widths. `pspg` allows for sidescrolling, which is great, except for use cases such as this.
Of course one could reset the pager to something else than `pspg`, but it would be really nice to be able to use a quick toggle within `pspg` instead to just simply fit the whole definition in the horizontal viewport. Would something like that be feasible?

**Comment by okbob** [comment]
út 26. 2. 2019 v 15:25 odesílatel Wicher <notifications@github.com> napsal:

> Sometimes, as when \d+-ing a view, one desires to select and copy-paste
> something that spans multiple screen widths. pspg allows for
> sidescrolling, which is great, except for use cases such as this.
> Of course one could reset the pager to something else than pspg, but it
> would be really nice to be able to use a quick toggle within pspg instead
> to just simply fit the whole definition in the horizontal viewport. Would
> something like that be feasible?
>

I can imagine some special exit mode, that send all data to stdout. Do you
think some like this?

**Comment by boerwastaken** [comment]
that's a very good & simple idea, and it would suffice!

**Comment by okbob** [comment]
please, check last commit - "Alt-q" command

**Comment by boerwastaken** [comment]
Tested - the output is still horizontally truncated. Running it as `pspg --force-uniborder --IGNORE-CASE -X --quit-if-one-screen --no-mouse -s 9` in pgcli 1.11.0 .

**Comment by okbob** [comment]
please, check it now.

Pavel

po 4. 3. 2019 v 8:37 odesílatel Wicher <notifications@github.com> napsal:

**Comment by boerwastaken** [comment]
Works! Thanks so much!

**Comment by okbob** [comment]
út 5. 3. 2019 v 3:32 odesílatel Wicher <notifications@github.com> napsal:

> Works! Thanks so much!
>
great

Pavel
