### ISSUE TITLE
Dump coma-separated list of columns

### ISSUE THREAD

**Issue by g0tar** [okbob/pspg#85]
I often find myself doing `SELECT * FROM ...` just to see there is too many data on screen. Then the horror begins - as there's no SQL syntax for `SELECT (* EXCEPT this, that and the other ones I don't need to see right now)` I have to manually pick columns from some output like `\d table` or `psql -AF, -c 'SELECT * FROM table LIMIT 0'` from another session. This gets harder with more complicated queries, involving multiple table JOINs, CTE etc.

There is the ToDo with in-pager column management, but while such function is pending I'd like to suggest some simple solution that might greately ease building queries. If only pspg could dump the column names in coma-separated list one could simply copy&paste this line (replacing the `*`) and easily remove the columns that are not required. There is a drawback that the header doesn't contain column source, so if there is `table_a.column` and `table_b.column` they are both returned as `column`, but this is still much faster to prepend table name only than building entire list manually. This would also ease reordering columns.

The result should be returned to the primary screen (not the -X alternate one), so this could be implemented as some quit mode - either the separate one (Q?) or appended to Alt-q output.

**Comment by okbob** [comment]
I don't think so this should be done by pspg pager. Maybe you can write some other pager for this purpose.

you can use new `\gdesc` command 
<pre>
\pset format unaligned
select ...
\gdesc
</pre>

**Comment by g0tar** [comment]
Nor switching pagers nor multiple commands are not comfortable enough, but if such feature is not upstreamable I will keep this one private too.
