### ISSUE TITLE
Feature request: support for 0-9 keys in addition to function keys

### ISSUE THREAD

**Issue by lacanoid** [okbob/pspg#88]
Keys 0-9 currently don't seem to do anything.

Perhaps it would be useful to make them do the same thing that function keys do, so you could press 9 in addition to F9 to open the menu,  etc... 
F10 could be mapped to 0.

This would make the program more useful on keyboards without function keys.
I've seen this somewhere, but I can't recall where.

**Comment by okbob** [comment]
No, keys 0..8 are used to set number of fixed columns.

If you have not functional keys, then you can use old (and pspg support it) trik. F9, F10 are effectively same like ESC 9, or ESC 0

**Comment by lacanoid** [comment]
I didn't know about the old ESC trick. Thanks!
