### ISSUE TITLE
Compilation again

### ISSUE THREAD

**Issue by loveencounterflow** [okbob/pspg#9]
I saw you released a new version with resizing implemented, so I got excited and tried

```bash
git clone https://github.com/okbob/pspg.git postgres-pager
cd postgres-pager
sudo apt-get install build-essential libreadline-dev libncurses5-dev libncursesw5-dev
gcc pager.c -o pager -L. -lncursesw
./pager -d
```
as per #1, but got 

```
pager.c: In function ‘main’:
pager.c:1641:26: error: ‘BUTTON5_PRESSED’ undeclared (first use in this function)
       if (event.bstate & BUTTON5_PRESSED)
                          ^
pager.c:1641:26: note: each undeclared identifier is reported only once for each function it appears in
```

instead. I'm using commit `e0a0aba17` here. Any suggestions?

**Comment by okbob** [comment]
probably your ncurses was compiled without mouse support. Please, try to check fresh code and comment row with `#define MOUSE_WHEEL_BUTTONS>     1`,

**Comment by loveencounterflow** [comment]
This worked; in `pager.c`, line 101:

```c
// #define MOUSE_WHEEL_BUTTONS      1
```

Thanks a lot. BTW I tried with both 

```bash
gcc pager.c -o pager -L. -lncurses
```

and 

```bash
gcc pager.c -o pager -L. -lncursesw
```

Both `ncurses` and `ncursesw` do not accept the `MOUSE_WHEEL_BUTTONS` to be defined. `ncurses` is not a viable option as it only renders US ASCII correctly; not even `latin-1` is supported (`ö` appears as `M-CM-6`?!?). Interestingly,

1) I can still use the mouse to click and select rows; only the wheel doesn't work;
2) `htop` shows the same behavior, so yes, `ncurses(w)` seems to globally lack mouse wheel support. 

I'm using version `6.0+20160213-1ubuntu1`; funny but the dev packages are called `libncursesw5-dev`.

**Comment by okbob** [comment]
You can have more version of same library - I am thinking so it is possibly to install dev ncurses 6 and linking pspg against this fresh library - https://stackoverflow.com/questions/3840218/how-to-specify-the-library-version-to-use-at-link-time
