### ISSUE TITLE
utf characters displayed wrongly

### ISSUE THREAD

**Issue by dk** [okbob/pspg#90]
Hello

I noticed that output that contains latin1 characters like øåæ is shown in a strange way, f.ex. å gets shown as M-CM-%, and ø as M-CM-8. My ncursers version is 6.1.20180127 from the latest ubuntu 18.
Is that a bug or misconfiguration of something?

**Comment by okbob** [comment]
probably your locale environment is not UTF8.  please, try to set LANG environment like `export LANG=cs_CZ.utf-8`. Second possible problem can be missing support of utf of ncurses library (pspg is linked against ncurses not against ncursesw). What is result of `pspg --version`

**Comment by dk** [comment]
Sorry didn't provide these. LANG is en_US.UTF-8. Version is 

pspg-1.6.5
with readline (version: 0x0700)
with integrated menu
ncurses version: 6.1, patch: 20180127
ncurses widechar num: 0

**Comment by dk** [comment]
...and yes, you're absolutiely correct:

configure: WARNING: The found ncurses library does not support wide-char.

The question is then, how do I enable that on standard ubuntu 18?

**Comment by okbob** [comment]
If I remember it well - it is separate deb dev package.

**Comment by dk** [comment]
I found out myself - one needs libncursesw5-dev and run "./configure --with-ncursesw" explicitly. It would be easier to find if "configure --help" said that, too.. Anyway thanks for quick help!

**Comment by okbob** [comment]
út 21. 5. 2019 v 15:17 odesílatel Dmitry Karasik <notifications@github.com>
napsal:

> I found out myself - one needs libncursesw5-dev and run "./configure
> --with-ncursesw" explicitly. It would be easier to find if "configure
> --help" said that, too.. Anyway thanks for quick help!
>
There is a chaos at libraries - there are two supported versions 5 and 6
and versions with and without support of wide chars. I am not a author of
autoconf module for ncurses, so I cannot to modify their result.

Usually the autoconf script should to prefer most modern with wide chars
support library. I can modify documentation of pspg - if you have some
proposal (notes) to build process, please, send it to me.

Regards

Pavel

**Comment by dk** [comment]
I don't have a proposal for the build as I myself am far from being autoconf specialist. But I'd suggest a line in the README.md with something like this:

= Bugs

1. If utf8 characters displayed wrongly, check if you have linked with a bad ncurses library. Check output of pspg --version | grep 'ncurses widechar' if it is 1 or 0. If it is 0, you may want to re-run './configure --with-ncursesw'. If that fails, install correct development libabries for ncursesw.

**Comment by okbob** [comment]
done
https://github.com/okbob/pspg/commit/9748c281063d325087f0cf206143b3ef0475db1b

út 21. 5. 2019 v 16:22 odesílatel Dmitry Karasik <notifications@github.com>
napsal:
