### ISSUE TITLE
Ubuntu install?

### ISSUE THREAD

**Issue by anthonydb** [okbob/pspg#91]
Apologies for my ignorance, but what's the install method for Ubuntu install? Compile from source?

**Comment by pmatseykanets** [comment]
@anthonydb you can use [linuxbrew](https://docs.brew.sh/Homebrew-on-Linux) as mentioned in [readme](https://github.com/okbob/pspg#linuxbrew) 

```
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
...
$ echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >>~/.profile
$ eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
...
$ brew --version
Homebrew 2.1.5
Homebrew/linuxbrew-core (git revision 04a1a; last commit 2019-06-12)

$ brew install pspg
...
$ pspg --version
pspg-1.6.5
with readline (version: 0x0800)
with integrated menu
ncurses version: 6.1, patch: 20180127
ncurses with wide char support

```

or compile from sources.

`apt` package is outdated

```
$ sudo apt-get update
...
$ apt-cache show pspg
Package: pspg
Architecture: amd64
Version: 0.9.3-1
Priority: optional
Section: universe/database
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
...
```

**Comment by okbob** [comment]
I tested Ubuntu 18 and you can install pspg 1.6.5 from pgdg repository https://wiki.postgresql.org/wiki/Apt

**Comment by jhancock** [comment]
Hi, I'm on ubuntu 18.04 and can't find the secret to installing pspg.

first try - 
```
me@server:~$ pspg

Command 'pspg' not found, but can be installed with:

sudo apt install pspg

me@server:~$ sudo apt install pspg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package pspg
```

second try (from cloned git repo git@github.com:okbob/pspg.git)
```
me@server:~$./configure
...
...
checking for a readline compatible library... no
configure: error: ncurses not found
```

I do have the postgres official repo added as per instructions here https://wiki.postgresql.org/wiki/Apt

I seem to have the nucurses dev libs installed:
```
me@server:~$ sudo apt-get install libncursesw5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libncursesw5 is already the newest version (6.1-1ubuntu1.18.04).
```

Any ideas?  thanks, Jon

**Comment by okbob** [comment]
I am not a expert on ubuntu, so I don't know where is a problem, but pspg is available on ubuntu https://packages.ubuntu.com/search?keywords=pspg.

If you want to build pspg from source, you should to install dev ncurses backages https://askubuntu.com/questions/270381/how-do-i-install-ncurses-header-files
