### ISSUE TITLE
User experience improvements

### ISSUE THREAD

**Issue by rightaway** [okbob/pspg#95]
When using `--line-numbers` the line number column for the header row should show the total number of rows (eg `70`) so you can see right away how many rows exist even when you're not using any of the bars.

The last line `(70 rows)` can then be omitted from the output since it isn't giving any additional information.

The last 2 line numbers should be omitted. The last is the one next to `(70 rows)` and the one before is for the border. So the only rows that should have a line number are actual result rows.

If I type `gg` I'm taken to the first row of actual results. But if I type `G` I go to the last row of output rather than the last row of results. It shouldn't be possible to select those last rows since they aren't actual result rows, as it works for the first rows that aren't results.

The highlighting in `simple` mode extends as wide as the table, as expected, but for other themes it extends as wide as the terminal (wider than the table). All themes should behave the same as `simple`.

**Comment by okbob** [comment]
I understand so when line numbers are visible, then some status informations are useless, but I would not to do UI more dynamical than it is now. Again I know so there are small inconsistency between `g` and `G`. It is from implementation reasons. It has sense to move cursor to header area. But some displayed data are not tabular only. You can look on output of `\d+ pg_class`. If you have table with lot of indexes, rules, .. then you need scroll (use cursor) after tabular data place.

From my perspective cursor in  'simple` mode is buggy and should be fixed. This question has not objective result - and I prefer wide cursor across terminal. Maybe in future I implement some option to be possible to choose what form of cursor should be used.
