### ISSUE TITLE
unrecognized option `--vertical-cursor'

### ISSUE THREAD

**Issue by soheilpro** [okbob/pspg#97]
Hi. Thanks for the great project.

I have version 1.6.8 installed on macOS 10.14.6 (via Homebrew):
```
pspg-1.6.8
with readline (version: 0x0800)
with integrated menu
ncurses version: 6.1, patch: 20180127
ncurses with wide char support
ncurses widechar num: 0
```

but the `--vertical-cursor` option is not available:
```
pspg: unrecognized option `--vertical-cursor'
Try pspg --help
```

**Comment by okbob** [comment]
Hi

po 26. 8. 2019 v 13:24 odesílatel Soheil Rashidi <notifications@github.com>
napsal:

> Hi. Thanks for the great project.
>
> I have version 1.6.8 installed on macOS 10.14.6 (via Homebrew):
>
> pspg-1.6.8
> with readline (version: 0x0800)
> with integrated menu
> ncurses version: 6.1, patch: 20180127
> ncurses with wide char support
> ncurses widechar num: 0
>
> but the --vertical-cursor option is not available:
>
> pspg: unrecognized option `--vertical-cursor'
> Try pspg --help
>
>
you need to use master branch (1.7.0). 1.6.8 doesn't support this feature.

Pavel

**Comment by soheilpro** [comment]
OK, thanks.

Any idea when then next version binaries will be released?

**Comment by okbob** [comment]
po 26. 8. 2019 v 15:04 odesílatel Soheil Rashidi <notifications@github.com>
napsal:

> OK, thanks.
>
> Any idea when then next version binaries will be released?
>

about 1 month

You can compile master branch from source code, it should not be
complicated on any unix like platform

**Comment by soheilpro** [comment]
Thanks.
