### ISSUE TITLE
Minor compilation warning

### ISSUE THREAD

**Issue by turnstep** [okbob/pspg#98]
MVEVENT->bstate is an unsigned long (at least in my version of ncurses), so the sprintf at line 2200 of src/pspg.c (as of 345812d9b478aa08342943a6e3970b954299bc9f) throws a warning. Changing it to %08lx fixes this.

gcc: 6.3.0
libncursesw5-dev : 6.0+20161126-1+deb9u2

**Comment by okbob** [comment]
Unfortunately it is platform depend - on linux it is mmask_t (unsigned int). So it cannot be fixed. But it is not too high issue. This part is in debug code - and almost time this code is unused. You can see this warning, because I do lot of debug work in master branch

**Comment by okbob** [comment]
It should be fixed now.

**Comment by thorstenkampe** [comment]
Just for the record: there are dozens of warnings from GCC (8.3.0) regarding "unsigned conversion from ‘int’ to ‘short unsigned int’ changes value" in `unicode.c`. Also a few "implicit declaration of function" in `pspg.c` and `print.c`.

**Comment by okbob** [comment]
čt 12. 9. 2019 v 8:16 odesílatel Thorsten Kampe <notifications@github.com>
napsal:

> Just for the record: there are dozens of warnings from GCC (8.3.0)
> regarding "unsigned conversion from ‘int’ to ‘short unsigned int’ changes
> value" in unicode.c. Also a few "implicit declaration of function" in
> pspg.c and print.c.
>
please, can you attach gcc output and send some info about your platform

I use gcc 9.2.1 on fresh fedora with -wall on 64bit fresh fedora, but I
have not possibility to check other platforms.

**Comment by thorstenkampe** [comment]
Attaching the output of make (`configure` generates no warning or error).
[make.log](https://github.com/okbob/pspg/files/3604087/make.log)

**Comment by okbob** [comment]
Thank you

what platform do you use?

čt 12. 9. 2019 v 8:52 odesílatel Thorsten Kampe <notifications@github.com>
napsal:

**Comment by thorstenkampe** [comment]
I'm using Cygwin 3.0.7 64-bit on Windows 10 64-bit.
